/* ==========================================================================
   Espontáneos Travel — Conserje con Jenny: base de conocimiento (ES/EN/FR/DE/PT)
   + strings de interfaz. Zero-cost, estático. Editable y expandible (IA luego).
   Placeholders que rellena concierge.js: {name} {region} {guide} {guideLangs}
   {host} {hotel} {hotelArea}
   ========================================================================== */

const CUI = {
  es: {
    brand: "Conserje de viaje", sub: "Espontáneos Travel",
    greet: "¡Hola {name}! 👋 Soy Jenny, tu anfitriona durante tu viaje por {region}. Estoy contigo 24/7. ¿En qué te ayudo hoy?",
    menu_prompt: "Elige un tema o escríbenos:",
    next_stop: "Tu próxima parada", itinerary: "Tu itinerario", trip_done: "¡Tu viaje está completo! Gracias por viajar con nosotros 💚",
    status: "Reserva", party: "Viajeros", guide: "Tu guía", hotel: "Tu hotel", today: "Hoy", tomorrow: "Mañana",
    enter_code: "Ingresa tu código de reserva", go: "Entrar", not_found: "No encontramos esa reserva. Revisa el código o escríbenos por WhatsApp.",
    back: "↩ Menú", wa_host: "Escribir a mi anfitrión", call_host: "Llamar al anfitrión", call_driver: "Llamar al conductor",
    maps_btn: "Abrir en el mapa", foot: "Respuestas guiadas · tu anfitrión confirma los detalles",
    wa_open: "Abrir WhatsApp", more: "¿Algo más? Elige otra opción 👇",
    m_schedule: "🗓️ Mis horarios", m_change: "⏰ Cambiar un horario", m_taxi: "🚕 Pedir taxi", m_lost: "🧭 Estoy lejos / perdido",
    m_restaurants: "🍽️ Restaurantes", m_money: "💱 Dinero / cambio", m_weather: "🌤️ Clima", m_clothing: "🧥 Qué ropa",
    m_diet: "🥗 Comida / dieta", m_access: "♿ Accesibilidad", m_health: "💊 Salud / medicamentos", m_wifi: "📶 Wifi / señal",
    m_guide: "🧑‍🏫 Mi guía", m_pack: "🎒 Qué llevar", m_tips: "💵 Propinas", m_phrases: "🗣️ Frases en español",
    m_reco: "⭐ Recomendaciones", m_emergency: "🚨 Emergencias", m_host: "💬 Hablar con mi anfitrión",
    wa_change: "Hola, soy {name} (reserva {code}). Quiero *cambiar un horario* de mi itinerario:",
    wa_taxi: "Hola, soy {name} (reserva {code}). ¿Me ayudan a *pedir un taxi*?",
    wa_lost: "Hola, soy {name} (reserva {code}). *Necesito ayuda para ubicarme.*",
    wa_access: "Hola, soy {name} (reserva {code}). Necesito *apoyo de accesibilidad* (silla de ruedas / coche para bebé / otro):",
    wa_generic: "Hola, soy {name} (reserva {code}). Tengo una consulta:"
  },
  en: {
    brand: "Travel concierge", sub: "Espontáneos Travel",
    greet: "Hi {name}! 👋 I'm Jenny, your host during your trip around {region}. I'm with you 24/7. How can I help today?",
    menu_prompt: "Pick a topic or message us:",
    next_stop: "Your next stop", itinerary: "Your itinerary", trip_done: "Your trip is complete! Thanks for travelling with us 💚",
    status: "Booking", party: "Travellers", guide: "Your guide", hotel: "Your hotel", today: "Today", tomorrow: "Tomorrow",
    enter_code: "Enter your booking code", go: "Enter", not_found: "We couldn't find that booking. Check the code or message us on WhatsApp.",
    back: "↩ Menu", wa_host: "Message my host", call_host: "Call the host", call_driver: "Call the driver",
    maps_btn: "Open in maps", foot: "Guided answers · your host confirms the details",
    wa_open: "Open WhatsApp", more: "Anything else? Pick another option 👇",
    m_schedule: "🗓️ My schedule", m_change: "⏰ Change a time", m_taxi: "🚕 Get a taxi", m_lost: "🧭 I'm far / lost",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Money / exchange", m_weather: "🌤️ Weather", m_clothing: "🧥 What to wear",
    m_diet: "🥗 Food / diet", m_access: "♿ Accessibility", m_health: "💊 Health / meds", m_wifi: "📶 Wi-Fi / signal",
    m_guide: "🧑‍🏫 My guide", m_pack: "🎒 What to pack", m_tips: "💵 Tipping", m_phrases: "🗣️ Spanish phrases",
    m_reco: "⭐ Recommendations", m_emergency: "🚨 Emergencies", m_host: "💬 Talk to my host",
    wa_change: "Hi, I'm {name} (booking {code}). I'd like to *change a time* in my itinerary:",
    wa_taxi: "Hi, I'm {name} (booking {code}). Can you help me *get a taxi*?",
    wa_lost: "Hi, I'm {name} (booking {code}). *I need help finding my way.*",
    wa_access: "Hi, I'm {name} (booking {code}). I need *accessibility support* (wheelchair / baby seat / other):",
    wa_generic: "Hi, I'm {name} (booking {code}). I have a question:"
  },
  fr: {
    brand: "Conciergerie de voyage", sub: "Espontáneos Travel",
    greet: "Bonjour {name} ! 👋 Je suis Jenny, votre hôtesse pendant votre voyage dans {region}. Disponible 24/7. Comment puis-je aider aujourd'hui ?",
    menu_prompt: "Choisissez un thème ou écrivez-nous :",
    next_stop: "Votre prochaine étape", itinerary: "Votre itinéraire", trip_done: "Votre voyage est terminé ! Merci d'avoir voyagé avec nous 💚",
    status: "Réservation", party: "Voyageurs", guide: "Votre guide", hotel: "Votre hôtel", today: "Aujourd'hui", tomorrow: "Demain",
    enter_code: "Saisissez votre code de réservation", go: "Entrer", not_found: "Réservation introuvable. Vérifiez le code ou écrivez-nous sur WhatsApp.",
    back: "↩ Menu", wa_host: "Écrire à mon hôte", call_host: "Appeler l'hôte", call_driver: "Appeler le chauffeur",
    maps_btn: "Ouvrir la carte", foot: "Réponses guidées · votre hôte confirme les détails",
    wa_open: "Ouvrir WhatsApp", more: "Autre chose ? Choisissez 👇",
    m_schedule: "🗓️ Mes horaires", m_change: "⏰ Changer un horaire", m_taxi: "🚕 Un taxi", m_lost: "🧭 Je suis loin / perdu",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Argent / change", m_weather: "🌤️ Météo", m_clothing: "🧥 Quoi porter",
    m_diet: "🥗 Repas / régime", m_access: "♿ Accessibilité", m_health: "💊 Santé / médicaments", m_wifi: "📶 Wi-Fi / réseau",
    m_guide: "🧑‍🏫 Mon guide", m_pack: "🎒 À emporter", m_tips: "💵 Pourboires", m_phrases: "🗣️ Phrases en espagnol",
    m_reco: "⭐ Recommandations", m_emergency: "🚨 Urgences", m_host: "💬 Parler à mon hôte",
    wa_change: "Bonjour, je suis {name} (réservation {code}). Je souhaite *changer un horaire* :",
    wa_taxi: "Bonjour, je suis {name} (réservation {code}). Pouvez-vous m'aider à *trouver un taxi* ?",
    wa_lost: "Bonjour, je suis {name} (réservation {code}). *J'ai besoin d'aide pour m'orienter.*",
    wa_access: "Bonjour, je suis {name} (réservation {code}). J'ai besoin d'un *soutien d'accessibilité* (fauteuil / siège bébé / autre) :",
    wa_generic: "Bonjour, je suis {name} (réservation {code}). J'ai une question :"
  },
  de: {
    brand: "Reise-Concierge", sub: "Espontáneos Travel",
    greet: "Hallo {name}! 👋 Ich bin Jenny, Ihre Gastgeberin während Ihrer Reise durch {region}. 24/7 für Sie da. Wie kann ich heute helfen?",
    menu_prompt: "Wählen Sie ein Thema oder schreiben Sie uns:",
    next_stop: "Ihr nächster Halt", itinerary: "Ihr Programm", trip_done: "Ihre Reise ist abgeschlossen! Danke, dass Sie mit uns gereist sind 💚",
    status: "Buchung", party: "Reisende", guide: "Ihr Guide", hotel: "Ihr Hotel", today: "Heute", tomorrow: "Morgen",
    enter_code: "Buchungscode eingeben", go: "Los", not_found: "Buchung nicht gefunden. Prüfen Sie den Code oder schreiben Sie uns per WhatsApp.",
    back: "↩ Menü", wa_host: "Gastgeber schreiben", call_host: "Gastgeber anrufen", call_driver: "Fahrer anrufen",
    maps_btn: "In Karte öffnen", foot: "Geführte Antworten · Ihr Gastgeber bestätigt die Details",
    wa_open: "WhatsApp öffnen", more: "Noch etwas? Wählen Sie 👇",
    m_schedule: "🗓️ Meine Zeiten", m_change: "⏰ Zeit ändern", m_taxi: "🚕 Taxi", m_lost: "🧭 Weit weg / verirrt",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Geld / Wechsel", m_weather: "🌤️ Wetter", m_clothing: "🧥 Kleidung",
    m_diet: "🥗 Essen / Diät", m_access: "♿ Barrierefreiheit", m_health: "💊 Gesundheit / Medikamente", m_wifi: "📶 WLAN / Signal",
    m_guide: "🧑‍🏫 Mein Guide", m_pack: "🎒 Packliste", m_tips: "💵 Trinkgeld", m_phrases: "🗣️ Sätze auf Spanisch",
    m_reco: "⭐ Empfehlungen", m_emergency: "🚨 Notfälle", m_host: "💬 Mit Gastgeber sprechen",
    wa_change: "Hallo, ich bin {name} (Buchung {code}). Ich möchte eine *Uhrzeit ändern*:",
    wa_taxi: "Hallo, ich bin {name} (Buchung {code}). Können Sie mir ein *Taxi besorgen*?",
    wa_lost: "Hallo, ich bin {name} (Buchung {code}). *Ich brauche Hilfe bei der Orientierung.*",
    wa_access: "Hallo, ich bin {name} (Buchung {code}). Ich brauche *Barrierefreiheits-Unterstützung* (Rollstuhl / Babysitz / anderes):",
    wa_generic: "Hallo, ich bin {name} (Buchung {code}). Ich habe eine Frage:"
  },
  pt: {
    brand: "Concierge de viagem", sub: "Espontáneos Travel",
    greet: "Olá {name}! 👋 Sou a Jenny, sua anfitriã durante sua viagem por {region}. Estou com você 24/7. Como posso ajudar hoje?",
    menu_prompt: "Escolha um tema ou escreva:",
    next_stop: "Sua próxima parada", itinerary: "Seu itinerário", trip_done: "Sua viagem está completa! Obrigado por viajar conosco 💚",
    status: "Reserva", party: "Viajantes", guide: "Seu guia", hotel: "Seu hotel", today: "Hoje", tomorrow: "Amanhã",
    enter_code: "Digite seu código de reserva", go: "Entrar", not_found: "Reserva não encontrada. Verifique o código ou fale conosco no WhatsApp.",
    back: "↩ Menu", wa_host: "Falar com meu anfitrião", call_host: "Ligar para o anfitrião", call_driver: "Ligar para o motorista",
    maps_btn: "Abrir no mapa", foot: "Respostas guiadas · seu anfitrião confirma os detalhes",
    wa_open: "Abrir WhatsApp", more: "Mais alguma coisa? Escolha 👇",
    m_schedule: "🗓️ Meus horários", m_change: "⏰ Mudar um horário", m_taxi: "🚕 Pedir táxi", m_lost: "🧭 Estou longe / perdido",
    m_restaurants: "🍽️ Restaurantes", m_money: "💱 Dinheiro / câmbio", m_weather: "🌤️ Clima", m_clothing: "🧥 O que vestir",
    m_diet: "🥗 Comida / dieta", m_access: "♿ Acessibilidade", m_health: "💊 Saúde / remédios", m_wifi: "📶 Wi-Fi / sinal",
    m_guide: "🧑‍🏫 Meu guia", m_pack: "🎒 O que levar", m_tips: "💵 Gorjetas", m_phrases: "🗣️ Frases em espanhol",
    m_reco: "⭐ Recomendações", m_emergency: "🚨 Emergências", m_host: "💬 Falar com meu anfitrião",
    wa_change: "Olá, sou {name} (reserva {code}). Quero *mudar um horário* do meu itinerário:",
    wa_taxi: "Olá, sou {name} (reserva {code}). Podem me ajudar a *pedir um táxi*?",
    wa_lost: "Olá, sou {name} (reserva {code}). *Preciso de ajuda para me localizar.*",
    wa_access: "Olá, sou {name} (reserva {code}). Preciso de *apoio de acessibilidade* (cadeira de rodas / bebê conforto / outro):",
    wa_generic: "Olá, sou {name} (reserva {code}). Tenho uma dúvida:"
  }
};

/* Knowledge base: each topic has a menu key (maps to CUI m_*), an action type and a 5-lang answer.
   action: "info" | "wa:<waKey>" | "dyn:<name>" (handled in concierge.js) */
const CKB = [
  { id:"schedule", menu:"m_schedule", action:"dyn:schedule" },
  { id:"guide",    menu:"m_guide",    action:"dyn:guide" },
  { id:"change",   menu:"m_change",   action:"wa:wa_change",
    a:{ es:"Dime qué parada u hora quieres mover y a qué horario. Al confirmar, *avisamos al conductor/guía que te recoge* para que todo coincida. Toca el botón y lo gestionamos por WhatsApp.",
        en:"Tell me which stop or time you want to move and to when. Once confirmed, *we notify the driver/guide picking you up* so everything matches. Tap the button and we handle it on WhatsApp.",
        fr:"Dites-moi quelle étape ou heure déplacer et à quand. Après confirmation, *nous prévenons le chauffeur/guide* qui vous récupère. Touchez le bouton, on gère sur WhatsApp.",
        de:"Sagen Sie, welchen Halt/welche Zeit Sie verschieben möchten. Nach Bestätigung *informieren wir Fahrer/Guide*, der Sie abholt. Tippen Sie, wir regeln es per WhatsApp.",
        pt:"Diga qual parada ou horário mover e para quando. Após confirmar, *avisamos o motorista/guia* que te busca. Toque no botão e resolvemos no WhatsApp." } },
  { id:"taxi", menu:"m_taxi", action:"wa:wa_taxi",
    a:{ es:"En el Eje Cafetero funcionan taxis y apps como *inDrive, DiDi y Cabify*. Para seguridad y mejor precio, *tu anfitrión puede pedírtelo*: toca el botón, dinos dónde estás y te coordinamos uno.",
        en:"In the Coffee Region there are taxis and apps like *inDrive, DiDi and Cabify*. For safety and a better price, *your host can arrange one*: tap the button, tell us where you are and we'll sort it.",
        fr:"Dans la région du café il y a des taxis et apps comme *inDrive, DiDi, Cabify*. Pour la sécurité, *votre hôte peut en commander un* : touchez le bouton et indiquez où vous êtes.",
        de:"In der Kaffeeregion gibt es Taxis und Apps wie *inDrive, DiDi, Cabify*. Für Sicherheit *kann Ihr Gastgeber eines bestellen*: Tippen Sie und sagen Sie, wo Sie sind.",
        pt:"Na Região Cafeeira há táxis e apps como *inDrive, DiDi e Cabify*. Para segurança, *seu anfitrião pode pedir um*: toque no botão e diga onde está." } },
  { id:"lost", menu:"m_lost", action:"wa:wa_lost",
    a:{ es:"Tranquil@. Toca el botón, *comparte tu ubicación en WhatsApp* (clip 📎 → Ubicación → Ubicación actual) y te guiamos o enviamos a alguien. Si es urgente, llama a tu anfitrión.",
        en:"Don't worry. Tap the button, *share your location on WhatsApp* (clip 📎 → Location → Current location) and we'll guide you or send someone. If urgent, call your host.",
        fr:"Pas d'inquiétude. Touchez le bouton, *partagez votre position sur WhatsApp* (📎 → Position) et on vous guide. Si urgent, appelez votre hôte.",
        de:"Keine Sorge. Tippen Sie, *teilen Sie Ihren Standort auf WhatsApp* (📎 → Standort) und wir leiten Sie. Bei Dringlichkeit rufen Sie Ihren Gastgeber an.",
        pt:"Calma. Toque no botão, *compartilhe sua localização no WhatsApp* (📎 → Localização) e te guiamos. Se urgente, ligue para seu anfitrião." } },
  { id:"restaurants", menu:"m_restaurants", action:"maps:restaurants",
    a:{ es:"Cerca encuentras cocina típica (trucha, patacón, bandeja paisa) y cafés de especialidad. Toca para ver *restaurantes locales en el mapa*. ¿Quieres una recomendación según tu zona o dieta? Pregúntame.",
        en:"Nearby you'll find typical food (trout, patacón, bandeja paisa) and specialty coffee. Tap to see *local restaurants on the map*. Want a pick by area or diet? Just ask.",
        fr:"À proximité : cuisine typique (truite, patacón, bandeja paisa) et cafés de spécialité. Touchez pour voir *les restaurants sur la carte*. Une reco selon votre régime ? Demandez.",
        de:"In der Nähe: typische Küche (Forelle, Patacón, Bandeja Paisa) und Spezialitätenkaffee. Tippen für *Restaurants auf der Karte*. Empfehlung nach Diät? Fragen Sie.",
        pt:"Por perto: comida típica (truta, patacón, bandeja paisa) e cafés especiais. Toque para ver *restaurantes no mapa*. Quer uma indicação por dieta? É só pedir." } },
  { id:"money", menu:"m_money", action:"maps:casa de cambio",
    a:{ es:"La moneda es el *peso colombiano (COP)*. Se paga con tarjeta en hoteles y muchos sitios; lleva *efectivo* para pueblos y propinas. Hay cajeros y casas de cambio en Armenia, Pereira y Manizales. Toca para verlas en el mapa.",
        en:"The currency is the *Colombian peso (COP)*. Cards work in hotels and many places; carry *cash* for villages and tips. ATMs and exchange offices are in Armenia, Pereira and Manizales. Tap to see them on the map.",
        fr:"La monnaie est le *peso colombien (COP)*. Carte acceptée dans les hôtels ; prévoyez du *liquide* pour les villages et pourboires. Distributeurs et bureaux de change à Armenia, Pereira, Manizales.",
        de:"Währung ist der *kolumbianische Peso (COP)*. Karte in Hotels ok; *Bargeld* für Dörfer und Trinkgeld mitnehmen. Geldautomaten/Wechselstuben in Armenia, Pereira, Manizales.",
        pt:"A moeda é o *peso colombiano (COP)*. Cartão em hotéis e muitos lugares; leve *dinheiro* para vilarejos e gorjetas. Caixas e câmbios em Armenia, Pereira e Manizales." } },
  { id:"weather", menu:"m_weather", action:"info",
    a:{ es:"El Eje Cafetero es *primavera todo el año*: 18–26 °C de día, fresco en la noche y en zonas altas (Cocora, páramo). Llueve a ratos casi cualquier día. Revisa el clima del día en tu app del celular. ☀️🌧️",
        en:"The Coffee Region is *spring-like all year*: 18–26 °C by day, cool at night and in high areas (Cocora, páramo). Brief rain can happen any day. Check today's forecast on your phone. ☀️🌧️",
        fr:"La région du café, c'est le *printemps toute l'année* : 18–26 °C le jour, frais la nuit et en altitude (Cocora, páramo). Pluie brève possible. Vérifiez la météo sur votre téléphone. ☀️🌧️",
        de:"Die Kaffeeregion ist *ganzjährig frühlingshaft*: tagsüber 18–26 °C, nachts/in Höhen (Cocora, Páramo) kühl. Kurzer Regen jederzeit möglich. Wetter per Handy prüfen. ☀️🌧️",
        pt:"A Região Cafeeira é *primavera o ano todo*: 18–26 °C de dia, fresco à noite e em zonas altas (Cocora, páramo). Pode chover rápido. Veja a previsão no celular. ☀️🌧️" } },
  { id:"clothing", menu:"m_clothing", action:"info",
    a:{ es:"Lleva *ropa en capas*: camiseta + chaqueta liviana o impermeable, *zapatos cómodos/cerrados* para caminar, gorra, bloqueador y repelente. Para Cocora o páramo, abrígate más. 🥾🧥",
        en:"Dress in *layers*: t-shirt + light or waterproof jacket, *comfy closed shoes* for walking, cap, sunscreen and repellent. For Cocora or páramo, bring warmer layers. 🥾🧥",
        fr:"Habillez-vous *en couches* : t-shirt + veste légère/imperméable, *chaussures fermées confortables*, casquette, crème solaire, répulsif. Pour Cocora/páramo, plus chaud. 🥾🧥",
        de:"Kleidung im *Zwiebellook*: T-Shirt + leichte/wasserdichte Jacke, *bequeme geschlossene Schuhe*, Kappe, Sonnencreme, Mückenschutz. Für Cocora/Páramo wärmer. 🥾🧥",
        pt:"Use *camadas*: camiseta + jaqueta leve/impermeável, *calçado fechado confortável*, boné, protetor solar e repelente. Para Cocora/páramo, leve mais agasalho. 🥾🧥" } },
  { id:"diet", menu:"m_diet", action:"wa:wa_generic",
    a:{ es:"Hay opciones *vegetarianas, veganas y sin gluten* con aviso previo. Si tienes *alergias* o preferencias, cuéntanos y lo coordinamos con los restaurantes y fincas. Toca para avisarnos.",
        en:"There are *vegetarian, vegan and gluten-free* options with notice. If you have *allergies* or preferences, tell us and we'll coordinate with restaurants and farms. Tap to let us know.",
        fr:"Options *végétariennes, véganes et sans gluten* sur demande. *Allergies* ou préférences ? Dites-le, on coordonne avec restaurants et fermes. Touchez pour nous informer.",
        de:"*Vegetarische, vegane und glutenfreie* Optionen auf Vorbestellung. *Allergien*/Wünsche? Sagen Sie Bescheid, wir stimmen uns mit Restaurants/Fincas ab. Tippen zum Melden.",
        pt:"Há opções *vegetarianas, veganas e sem glúten* com aviso. *Alergias* ou preferências? Conte e coordenamos com restaurantes e fazendas. Toque para avisar." } },
  { id:"access", menu:"m_access", action:"wa:wa_access",
    a:{ es:"Creemos en el *turismo sin barreras* ♿. Según el recorrido coordinamos *silla de ruedas, coche para bebé, rutas y transporte accesibles y apoyo personal*. Cuéntanos qué necesitas y lo preparamos. Toca el botón.",
        en:"We believe in *barrier-free tourism* ♿. Depending on the tour we arrange *wheelchair, baby seat, accessible routes/transport and personal support*. Tell us what you need and we'll prepare it. Tap the button.",
        fr:"Nous croyons au *tourisme sans barrières* ♿. Selon l'excursion : *fauteuil, siège bébé, itinéraires/transport accessibles et accompagnement*. Dites vos besoins. Touchez le bouton.",
        de:"Wir glauben an *barrierefreien Tourismus* ♿. Je nach Tour organisieren wir *Rollstuhl, Babysitz, barrierefreie Wege/Transport und Begleitung*. Sagen Sie uns Ihren Bedarf. Tippen.",
        pt:"Acreditamos no *turismo sem barreiras* ♿. Conforme o passeio: *cadeira de rodas, bebê conforto, rotas/transporte acessíveis e apoio pessoal*. Diga o que precisa. Toque no botão." } },
  { id:"health", menu:"m_health", action:"info",
    a:{ es:"Recorridos suaves (fincas, pueblos, termales) son aptos para casi todos. Caminatas (Cocora, páramo) piden *condición física media* y hay *altura* (hasta ~3.000 m). Lleva tus *medicamentos personales*, hidratación y, si tienes una condición, avísanos para adaptar el ritmo. No somos servicio médico; ante emergencia, 123.",
        en:"Easy tours (farms, towns, hot springs) suit almost everyone. Hikes (Cocora, páramo) need *moderate fitness* and involve *altitude* (up to ~3,000 m). Bring your *personal meds*, stay hydrated and, if you have a condition, tell us to adapt the pace. We're not a medical service; in an emergency, dial 123.",
        fr:"Excursions faciles (fermes, villages, thermes) pour presque tous. Randos (Cocora, páramo) : *condition moyenne* et *altitude* (~3 000 m). Prenez vos *médicaments*, hydratez-vous ; une condition ? Prévenez-nous. Pas un service médical ; urgence : 123.",
        de:"Leichte Touren (Fincas, Dörfer, Thermen) für fast alle. Wanderungen (Cocora, Páramo): *mittlere Fitness* und *Höhe* (~3.000 m). *Eigene Medikamente* mitnehmen, trinken; bei Vorerkrankung Bescheid geben. Kein medizinischer Dienst; Notruf 123.",
        pt:"Passeios leves (fazendas, vilarejos, termas) servem a quase todos. Trilhas (Cocora, páramo): *preparo médio* e *altitude* (~3.000 m). Leve seus *remédios*, hidrate-se; se tiver condição, avise para adaptar o ritmo. Não somos serviço médico; emergência: 123." } },
  { id:"wifi", menu:"m_wifi", action:"info",
    a:{ es:"Hoteles y cafés tienen *wifi*. En fincas y zonas rurales la señal puede ser *limitada* (Claro suele tener mejor cobertura). Descarga mapas sin conexión y guarda este enlace. Tu anfitrión siempre está por WhatsApp.",
        en:"Hotels and cafés have *Wi-Fi*. On farms and rural areas signal can be *limited* (Claro tends to have better coverage). Download offline maps and save this link. Your host is always on WhatsApp.",
        fr:"Hôtels et cafés ont le *Wi-Fi*. Dans les fermes/zones rurales, le réseau peut être *limité* (Claro = meilleure couverture). Téléchargez des cartes hors-ligne. Votre hôte reste sur WhatsApp.",
        de:"Hotels/Cafés haben *WLAN*. Auf Fincas/ländlich kann das Signal *begrenzt* sein (Claro meist beste Abdeckung). Offline-Karten laden. Ihr Gastgeber ist immer per WhatsApp da.",
        pt:"Hotéis e cafés têm *Wi-Fi*. Em fazendas e zonas rurais o sinal pode ser *limitado* (Claro costuma ter melhor cobertura). Baixe mapas offline. Seu anfitrião está sempre no WhatsApp." } },
  { id:"pack", menu:"m_pack", action:"info",
    a:{ es:"Checklist 🎒: documento/pasaporte, efectivo (COP) y tarjeta, medicamentos, bloqueador y repelente, gorra/gafas, impermeable, zapatos cómodos, botella de agua, cargador/power bank y cámara. Para termales: *vestido de baño y toalla*.",
        en:"Checklist 🎒: ID/passport, cash (COP) and card, meds, sunscreen and repellent, cap/sunglasses, rain jacket, comfy shoes, water bottle, charger/power bank and camera. For hot springs: *swimsuit and towel*.",
        fr:"Checklist 🎒 : pièce d'identité, liquide (COP) et carte, médicaments, crème solaire, répulsif, casquette/lunettes, imperméable, chaussures confortables, gourde, chargeur et appareil photo. Thermes : *maillot et serviette*.",
        de:"Checkliste 🎒: Ausweis/Pass, Bargeld (COP) und Karte, Medikamente, Sonnencreme, Mückenschutz, Kappe/Brille, Regenjacke, bequeme Schuhe, Trinkflasche, Ladegerät/Powerbank, Kamera. Thermen: *Badesachen und Handtuch*.",
        pt:"Checklist 🎒: documento/passaporte, dinheiro (COP) e cartão, remédios, protetor e repelente, boné/óculos, capa de chuva, calçado confortável, garrafa de água, carregador/power bank e câmera. Termas: *roupa de banho e toalha*." } },
  { id:"tips", menu:"m_tips", action:"info",
    a:{ es:"La propina es *voluntaria*. En restaurantes suele sugerirse el 10% (puedes aceptarlo o no). A guías y conductores, si te gustó el servicio, una propina es muy apreciada. 💚",
        en:"Tipping is *voluntary*. Restaurants often suggest 10% (you may accept or decline). For guides and drivers, if you enjoyed the service, a tip is much appreciated. 💚",
        fr:"Le pourboire est *facultatif*. Les restaurants suggèrent souvent 10 % (libre à vous). Pour guides et chauffeurs, un pourboire est très apprécié. 💚",
        de:"Trinkgeld ist *freiwillig*. Restaurants schlagen oft 10 % vor (annehmen oder nicht). Für Guides/Fahrer ist ein Trinkgeld sehr willkommen. 💚",
        pt:"A gorjeta é *voluntária*. Restaurantes costumam sugerir 10% (você aceita ou não). Para guias e motoristas, se gostou, uma gorjeta é muito bem-vinda. 💚" } },
  { id:"phrases", menu:"m_phrases", action:"info",
    a:{ es:"¡Ya hablas español! 😄 Pero por si acaso: *Hola / Gracias / Por favor / ¿Cuánto cuesta? / ¿Dónde está el baño? / Un café, por favor / Ayuda*.",
        en:"Handy Spanish: *Hola* (hi) · *Gracias* (thanks) · *Por favor* (please) · *¿Cuánto cuesta?* (how much) · *¿Dónde está el baño?* (where's the toilet) · *Un café, por favor* · *Ayuda* (help).",
        fr:"Espagnol utile : *Hola* (bonjour) · *Gracias* (merci) · *Por favor* (s'il vous plaît) · *¿Cuánto cuesta?* (combien) · *¿Dónde está el baño?* (toilettes) · *Un café, por favor* · *Ayuda* (aide).",
        de:"Nützliches Spanisch: *Hola* (hallo) · *Gracias* (danke) · *Por favor* (bitte) · *¿Cuánto cuesta?* (wie viel) · *¿Dónde está el baño?* (Toilette) · *Un café, por favor* · *Ayuda* (Hilfe).",
        pt:"Espanhol útil: *Hola* (oi) · *Gracias* (obrigado) · *Por favor* · *¿Cuánto cuesta?* (quanto custa) · *¿Dónde está el baño?* (banheiro) · *Un café, por favor* · *Ayuda* (ajuda)." } },
  { id:"reco", menu:"m_reco", action:"info",
    a:{ es:"Imperdibles: *Valle de Cocora* (palma de cera), pueblos de colores *Salento y Filandia*, *café de origen* en finca, *termales* de Santa Rosa, miradores de la cordillera y *avistamiento de aves*. ¿Quieres algo fuera de lo común? Pregúntame por *Colombia inexplorada* y te armamos planes únicos.",
        en:"Must-sees: *Cocora Valley* (wax palms), colourful *Salento and Filandia*, *origin coffee* on a farm, *Santa Rosa hot springs*, mountain viewpoints and *birdwatching*. Want something off the beaten path? Ask about *unexplored Colombia* and we'll craft unique plans.",
        fr:"À ne pas manquer : *vallée de Cocora*, villages colorés *Salento et Filandia*, *café d'origine*, *thermes de Santa Rosa*, belvédères et *observation d'oiseaux*. Hors des sentiers ? Demandez la *Colombie inexplorée*.",
        de:"Highlights: *Cocora-Tal*, bunte Dörfer *Salento und Filandia*, *Ursprungskaffee*, *Thermen Santa Rosa*, Aussichtspunkte und *Vogelbeobachtung*. Abseits der Pfade? Fragen Sie nach dem *unerforschten Kolumbien*.",
        pt:"Imperdíveis: *Vale de Cocora*, vilarejos coloridos *Salento e Filandia*, *café de origem*, *termas de Santa Rosa*, mirantes e *observação de aves*. Quer algo fora do comum? Pergunte pela *Colômbia inexplorada*." } },
  { id:"emergency", menu:"m_emergency", action:"info",
    a:{ es:"🚨 Emergencias en Colombia: *123* (línea única). Policía 123 · Ambulancia 125 · Bomberos 119. Guarda también el número de tu anfitrión (abajo). Si estás en un recorrido, avisa a tu guía de inmediato.",
        en:"🚨 Emergencies in Colombia: *123* (single line). Police 123 · Ambulance 125 · Fire 119. Also save your host's number (below). On a tour, alert your guide immediately.",
        fr:"🚨 Urgences en Colombie : *123*. Police 123 · Ambulance 125 · Pompiers 119. Enregistrez aussi le numéro de votre hôte (ci-dessous). En excursion, prévenez votre guide.",
        de:"🚨 Notfälle in Kolumbien: *123*. Polizei 123 · Krankenwagen 125 · Feuerwehr 119. Speichern Sie auch die Nummer Ihres Gastgebers (unten). Auf Tour sofort Guide informieren.",
        pt:"🚨 Emergências na Colômbia: *123*. Polícia 123 · Ambulância 125 · Bombeiros 119. Salve também o número do seu anfitrião (abaixo). Em passeio, avise seu guia na hora." } }
];

/* Strings extra de interfaz (input de texto libre) */
const CUI_EXTRA = {
  es: { ask_ph: "Escríbeme tu pregunta…", send: "Enviar", more_topics: "➕ Más temas", no_match: "No estoy 100% segura de eso, pero tu anfitrión te responde al instante 👇", wa_q: "Hola, soy {name} (reserva {code}). Mi pregunta es:" },
  en: { ask_ph: "Type your question…", send: "Send", more_topics: "➕ More topics", no_match: "I'm not 100% sure about that, but your host will answer right away 👇", wa_q: "Hi, I'm {name} (booking {code}). My question is:" },
  fr: { ask_ph: "Écrivez votre question…", send: "Envoyer", more_topics: "➕ Plus de thèmes", no_match: "Je n'en suis pas tout à fait sûre, mais votre hôte vous répond tout de suite 👇", wa_q: "Bonjour, je suis {name} (réservation {code}). Ma question :" },
  de: { ask_ph: "Schreiben Sie Ihre Frage…", send: "Senden", more_topics: "➕ Mehr Themen", no_match: "Da bin ich nicht ganz sicher, aber Ihr Gastgeber antwortet sofort 👇", wa_q: "Hallo, ich bin {name} (Buchung {code}). Meine Frage:" },
  pt: { ask_ph: "Escreva sua pergunta…", send: "Enviar", more_topics: "➕ Mais temas", no_match: "Não tenho 100% de certeza disso, mas seu anfitrião responde na hora 👇", wa_q: "Olá, sou {name} (reserva {code}). Minha pergunta é:" }
};

/* Palabras clave (sin tildes, minúsculas) para entender preguntas escritas libremente */
const CKB_KW = {
  schedule:["horario","horarios","itinerario","agenda","programa","plan","schedule","itinerary","time","times","horaire","zeitplan","programacao"],
  guide:["guia","guide","guida","fuhrer","idioma del guia","mi guia","quien es mi guia"],
  change:["cambiar","cambio","mover","reprogramar","change","reschedule","modifier","andern","mudar","otra hora","otro dia"],
  taxi:["taxi","cab","uber","didi","indrive","cabify","transporte","carro","auto","ride","vtc"],
  lost:["perdido","perdida","lejos","no encuentro","ubicarme","lost","far","i am far","orientacion","perdu","verirrt","perdido do hotel"],
  restaurants:["restaurante","restaurantes","comer","comida","restaurant","food","eat","donde comer","almuerzo","cena","dinner","lunch","manger"],
  money:["dinero","plata","cambio","cajero","atm","efectivo","peso","pesos","money","exchange","cash","currency","banco","geld","argent","dinheiro"],
  weather:["clima","tiempo","temperatura","weather","lluvia","rain","meteo","wetter","frio","calor","grados"],
  clothing:["ropa","vestir","que llevo puesto","clothes","wear","what to wear","vetements","kleidung","roupa","zapatos","chaqueta","abrigo"],
  diet:["dieta","vegetariano","vegano","vegan","gluten","alergia","alergias","allergy","diet","celiaco","intolerancia","sin carne","regime"],
  access:["silla de ruedas","wheelchair","accesible","accesibilidad","discapacidad","movilidad","coche de bebe","coche bebe","baby seat","stroller","barreras","rollstuhl","cadeira de rodas","sin barreras","fauteuil"],
  health:["salud","medico","medicamento","medicamentos","medicina","pastillas","health","meds","medicine","condicion fisica","fitness","altura","soroche","enfermo","dolor","gesundheit","sante"],
  wifi:["wifi","wi-fi","internet","senal","señal","signal","datos","cobertura","red","conexion"],
  pack:["que llevar","empacar","maleta","equipaje","pack","packing","luggage","que meto","que empaco","valise","koffer","bagagem","llevar"],
  tips:["propina","propinas","tip","tipping","gratification","trinkgeld","gorjeta","cuanto dejar"],
  phrases:["frases","espanol","palabras","idioma","como se dice","phrases","spanish","words","language","hablar"],
  reco:["recomendacion","recomendaciones","que hacer","que ver","sugerencias","recommend","what to do","must see","consejos","tips de viaje","inexplorada","unexplored","fuera de lo comun"],
  emergency:["emergencia","emergencias","emergency","ayuda urgente","policia","ambulancia","hospital","urgence","notfall","emergencia medica","123"],
  airport:["aeropuerto","airport","vuelo","vuelos","flight","axm","pei","el eden","matecana","aeroport","flughafen","traslado aeropuerto","del aeropuerto"],
  checkin:["check in","check-in","checkin","check out","checkout","entrada hotel","salida hotel","guardar maletas","equipaje hotel","hora de entrada","late checkout"],
  sim:["sim","chip","esim","datos moviles","mobile data","phone","celular","claro","tigo","movistar","internet movil","numero local"],
  power:["enchufe","toma","corriente","electricidad","voltaje","adaptador","plug","socket","power","voltage","adapter","110","steckdose"],
  water:["agua","water","agua potable","tomar agua","drinking water","grifo","wasser","agua de la llave"],
  altitude:["altura","altitud","soroche","mal de altura","altitude","altitude sickness","mareo","oxigeno","hohenkrankheit"],
  safety:["seguridad","seguro","peligro","safe","safety","is it safe","robo","estafa","scam","cuidado","danger","sicherheit"],
  pharmacy:["farmacia","droguería","drogueria","pharmacy","drugstore","medicina","pastillas","pharmacie","apotheke","farmacia cercana"],
  children:["niños","ninos","niño","bebe","bebes","hijos","children","kids","baby","family","familia","apto para niños","kinder","criancas"],
  souvenirs:["souvenir","souvenirs","recuerdos","comprar","artesania","artesanias","regalos","shopping","que comprar","cafe para llevar","handicraft","geschenke"],
  includes:["incluye","que incluye","incluido","included","what is included","mi plan incluye","inclus","inklusive","inclui"],
  insurance:["seguro","seguro de viaje","asistencia medica","insurance","travel insurance","assurance","versicherung","seguro medico","cobertura"],
  vaccines:["vacuna","vacunas","fiebre amarilla","vaccine","vaccines","yellow fever","vaccin","impfung","vacina"],
  extend:["agregar","extender","mas dias","mas experiencias","add","extend","extra","upgrade","otra experiencia","mas tours","prolongar"],
  feedback:["reseña","resena","review","opinion","calificar","feedback","google","estrellas","avis","bewertung","avaliacao"],
  transport:["moverme","transporte","jeep","willys","bus","buseta","como llego","como ir","get around","how to get","transport","chiva","colectivo","intermunicipal","fahren"],
  bathrooms:["baño","banos","baños","bano","toilet","restroom","wc","bathroom","toilettes","banheiro","sanitario"],
  photography:["foto","fotos","fotografia","camara","drone","dron","photo","photography","camera","appareil photo","kamera","permiso de fotos"],
  pets:["mascota","mascotas","perro","gato","pet","pets","dog","haustier","cachorro","animal de compania","pet friendly"],
  laundry:["lavar","lavanderia","ropa sucia","laundry","wash","washing","lessive","wasche","lavar roupa","limpiar ropa"],
  cancellation:["cancelar","cancelacion","reembolso","devolucion","cancel","refund","annuler","stornieren","politica de cancelacion","cambiar reserva"],
  nightlife:["noche","rumba","bar","bares","discoteca","nightlife","night","fiesta","vida nocturna","drinks","copas"],
  holidays:["festivo","festivos","feriado","holiday","temporada alta","high season","puente","vacaciones","feiertag","semana santa"],
  apps:["app","apps","aplicacion","aplicaciones","que apps","which apps","maps","mapa offline","descargar apps"],
  distances:["distancia","distancias","cuanto se demora","cuanto tarda","how far","how long","cuanto hay","tiempo de viaje","km","entfernung"],
  dollars:["dolar","dolares","euro","euros","pagar en dolares","pay in dollars","usd","eur","moneda extranjera","cambio dolar"],
  travelers:["adulto mayor","tercera edad","viajo solo","viajo sola","grupo","grupos","family","elderly","senior","solo","embarazada","pregnant","empresa","corporativo"],
  hospital:["hospital","clinica","medico urgente","doctor","urgencias","hospital cercano","notaufnahme","pronto socorro","ambulancia"],
  locallang:["hablan ingles","english","idioma local","speak english","do they speak","sprechen englisch","falam ingles","entienden ingles"],
  lostitem:["olvide","perdi","objeto perdido","lost item","i lost","deje olvidado","perdi algo","verloren","esqueci","dejé"],
  visa:["visa","visado","pasaporte","entrar a colombia","entry","requisitos","immigration","migracion","sello","90 dias","necesito visa","passport","einreise","visto"],
  food:["comida tipica","que comer","platos tipicos","bandeja paisa","trucha","typical food","what to eat","dishes","gastronomia","sancocho","arepa","lechona","essen","comida local","what food"],
  drinks:["bebida","bebidas","tomar","drink","drinks","aguardiente","ron","jugo","aguapanela","boisson","getranke","chocolate","limonada"],
  payment:["como pago","como pagar","anticipo","deposito","how to pay","deposit","payment","medios de pago","nequi","pse","datos de pago","pagar reserva","paiement","zahlung","como abono"],
  culture:["cultura","costumbres","etiqueta","como saludar","customs","etiquette","greeting","como se comportan","kultur","saludo","que no hacer"],
  swimming:["nadar","piscina","banarse","banarme","swim","swimming","pool","rio para nadar","vestido de bano","nager","schwimmen","me puedo banar"],
  rain:["lluvia","llueve","si llueve","rain","raining","what if it rains","plan b","pluie","regen","chuva","paraguas","impermeable"],
  coffee:["cafe","coffee","cafe de origen","tour de cafe","coffee tour","comprar cafe","cata de cafe","kaffee","cafe especial","finca de cafe"],
  alcohol:["alcohol","cerveza","beer","aguardiente","ron","edad legal","drinking age","fumar","smoking","alkohol","alcool","cigarrillo","tomar trago"],
  lgbt:["lgbt","gay","lesbiana","queer","homosexual","trans","pareja del mismo sexo","lgbtq","gay friendly","gay-friendly"],
  duration:["cuanto dura","duracion","how long","duration","cuantas horas","medio dia","dia completo","half day","full day","dauer","quanto dura","tiempo del tour"],
  privatetours:["privado","privada","private","tour privado","shared","compartido","solo mi grupo","exclusivo","prive","privat","grupo privado","personalizado"],
  flightdelay:["vuelo retrasado","retraso","flight delay","delayed","mi vuelo cambio","flight changed","retard vol","flugverspatung","voo atrasado","vuelo se retraso"]
};

/* Temas adicionales (sin botón en el menú; se llegan escribiendo la pregunta) */
const CKB_EXTRA = [
  { id:"airport", action:"info", a:{
    es:"Los aeropuertos son *El Edén (AXM, Armenia)* y *Matecaña (PEI, Pereira)*, a 20–40 min de la mayoría de hoteles. Coordinamos tu *traslado*; dinos tu vuelo y hora y te recogemos.",
    en:"The airports are *El Edén (AXM, Armenia)* and *Matecaña (PEI, Pereira)*, 20–40 min from most hotels. We arrange your *transfer*; send us your flight and time and we'll pick you up.",
    fr:"Aéroports : *El Edén (AXM, Armenia)* et *Matecaña (PEI, Pereira)*, à 20–40 min des hôtels. Nous organisons votre *transfert* ; envoyez vol et heure.",
    de:"Flughäfen: *El Edén (AXM, Armenia)* und *Matecaña (PEI, Pereira)*, 20–40 Min. zu den Hotels. Wir organisieren Ihren *Transfer*; senden Sie Flug und Zeit.",
    pt:"Aeroportos: *El Edén (AXM, Armenia)* e *Matecaña (PEI, Pereira)*, a 20–40 min dos hotéis. Organizamos seu *traslado*; envie voo e horário." } },
  { id:"checkin", action:"info", a:{
    es:"Check-in en hoteles suele ser desde las *15:00* y check-out hasta las *12:00*. Guardamos tu equipaje si llegas antes o sales después. ¿Necesitas late check-out? Avísanos.",
    en:"Hotel check-in is usually from *3 pm* and check-out until *12 pm*. We can store your luggage if you arrive early or leave late. Need a late check-out? Tell us.",
    fr:"Check-in dès *15h*, check-out jusqu'à *12h*. Bagages gardés si besoin. Late check-out ? Dites-le.",
    de:"Check-in meist ab *15 Uhr*, Check-out bis *12 Uhr*. Gepäckaufbewahrung möglich. Späten Check-out? Sagen Sie Bescheid.",
    pt:"Check-in geralmente a partir das *15h*, check-out até *12h*. Guardamos a bagagem se precisar. Late check-out? Avise." } },
  { id:"sim", action:"info", a:{
    es:"Puedes comprar una *SIM local* (Claro, Tigo o Movistar) con tu pasaporte — datos muy baratos. O una *eSIM* antes de viajar. En el aeropuerto y centros comerciales las venden.",
    en:"You can buy a *local SIM* (Claro, Tigo or Movistar) with your passport — data is very cheap. Or an *eSIM* before you travel. Sold at the airport and malls.",
    fr:"Achetez une *SIM locale* (Claro, Tigo, Movistar) avec passeport — données bon marché. Ou une *eSIM* avant le départ. En vente à l'aéroport.",
    de:"Kaufen Sie eine *lokale SIM* (Claro, Tigo, Movistar) mit Reisepass — günstige Daten. Oder eine *eSIM* vor der Reise. Am Flughafen erhältlich.",
    pt:"Compre um *SIM local* (Claro, Tigo ou Movistar) com passaporte — dados baratos. Ou um *eSIM* antes de viajar. Vendem no aeroporto." } },
  { id:"power", action:"info", a:{
    es:"La corriente es *110V* y los enchufes son *tipo A/B* (iguales a EE. UU.). Si vienes de Europa, trae un *adaptador*.",
    en:"Power is *110V* and plugs are *type A/B* (same as the US). Coming from Europe? Bring an *adapter*.",
    fr:"Courant *110V*, prises *type A/B* (comme aux USA). Depuis l'Europe ? Prenez un *adaptateur*.",
    de:"Strom *110V*, Stecker *Typ A/B* (wie USA). Aus Europa? *Adapter* mitbringen.",
    pt:"Energia *110V*, tomadas *tipo A/B* (como nos EUA). Vindo da Europa? Traga um *adaptador*." } },
  { id:"water", action:"info", a:{
    es:"El agua del grifo es *potable en las ciudades* (Armenia, Pereira, Manizales). En zonas rurales, mejor *agua embotellada*. Lleva tu botella y la rellenamos.",
    en:"Tap water is *safe in the cities* (Armenia, Pereira, Manizales). In rural areas, prefer *bottled water*. Bring your bottle and we'll refill it.",
    fr:"Eau du robinet *potable en ville*. En zone rurale, préférez l'*eau en bouteille*. Apportez votre gourde.",
    de:"Leitungswasser ist *in den Städten trinkbar*. Ländlich besser *Flaschenwasser*. Bringen Sie Ihre Flasche mit.",
    pt:"Água da torneira é *potável nas cidades*. Em zonas rurais, prefira *água engarrafada*. Traga sua garrafa." } },
  { id:"altitude", action:"info", a:{
    es:"La mayoría de recorridos están a altura cómoda. En zonas altas (*páramo ~3.000 m*) puede dar leve *soroche*: sube despacio, hidrátate y un *té de coca* ayuda. Si tienes condición cardiaca/respiratoria, consúltalo con tu médico y avísanos.",
    en:"Most tours are at comfortable altitude. In high areas (*páramo ~3,000 m*) mild *altitude sickness* can occur: go slowly, hydrate and *coca tea* helps. With a heart/breathing condition, check with your doctor and tell us.",
    fr:"La plupart des excursions sont à altitude confortable. En altitude (*páramo ~3 000 m*), léger *mal des montagnes* possible : montez doucement, hydratez-vous, le *thé de coca* aide. Condition cardiaque/respiratoire ? Consultez votre médecin.",
    de:"Die meisten Touren sind in angenehmer Höhe. In Höhenlagen (*Páramo ~3.000 m*) leichte *Höhenkrankheit* möglich: langsam gehen, trinken, *Coca-Tee* hilft. Bei Herz-/Atemproblemen Arzt fragen und uns informieren.",
    pt:"A maioria dos passeios está em altitude confortável. Em zonas altas (*páramo ~3.000 m*) pode dar leve *mal de altitude*: suba devagar, hidrate-se e *chá de coca* ajuda. Com condição cardíaca/respiratória, consulte seu médico." } },
  { id:"safety", action:"info", a:{
    es:"El Eje Cafetero es una región *tranquila y muy turística*. Con precauciones normales estarás bien: usa taxis/apps, cuida tus pertenencias, evita mostrar objetos de valor y sigue las indicaciones de tu guía. Cualquier duda, escríbeme.",
    en:"The Coffee Region is *calm and very touristy*. With normal precautions you'll be fine: use taxis/apps, mind your belongings, avoid flashing valuables and follow your guide. Any doubt, message me.",
    fr:"La région du café est *calme et très touristique*. Avec des précautions normales, tout ira bien : taxis/apps, surveillez vos affaires, pas d'objets de valeur en vue, suivez votre guide.",
    de:"Die Kaffeeregion ist *ruhig und sehr touristisch*. Mit normaler Vorsicht alles gut: Taxis/Apps nutzen, auf Wertsachen achten, nichts offen zeigen, dem Guide folgen.",
    pt:"A Região Cafeeira é *tranquila e muito turística*. Com precauções normais você fica bem: use táxis/apps, cuide dos pertences, evite exibir objetos de valor e siga seu guia." } },
  { id:"pharmacy", action:"info", a:{
    es:"Hay *droguerías (farmacias)* en todos los pueblos; muchos medicamentos se venden sin receta. Cadenas conocidas: Cruz Verde, Farmatodo, La Rebaja. Si necesitas una cercana, escríbeme tu ubicación.",
    en:"There are *pharmacies (droguerías)* in every town; many meds are sold without prescription. Known chains: Cruz Verde, Farmatodo, La Rebaja. Need a nearby one? Send me your location.",
    fr:"*Pharmacies (droguerías)* dans chaque ville ; beaucoup de médicaments sans ordonnance. Chaînes : Cruz Verde, Farmatodo, La Rebaja. Besoin d'une proche ? Envoyez votre position.",
    de:"In jedem Ort gibt es *Apotheken (droguerías)*; viele Medikamente ohne Rezept. Ketten: Cruz Verde, Farmatodo, La Rebaja. Eine in der Nähe? Senden Sie Ihren Standort.",
    pt:"Há *farmácias (droguerías)* em todas as cidades; muitos remédios sem receita. Redes: Cruz Verde, Farmatodo, La Rebaja. Precisa de uma perto? Mande sua localização." } },
  { id:"children", action:"wa:wa_generic", a:{
    es:"¡Viajar en familia es ideal aquí! Fincas, parques temáticos y pueblos son perfectos para *niños*. Dinos las edades y preparamos sillas, ritmo y actividades adecuadas. Toca para contarnos.",
    en:"Family travel is great here! Farms, theme parks and towns are perfect for *kids*. Tell us their ages and we'll arrange seats, pace and suitable activities. Tap to let us know.",
    fr:"Voyager en famille est parfait ici ! Fermes, parcs et villages pour les *enfants*. Dites les âges et on prépare sièges, rythme et activités. Touchez pour nous dire.",
    de:"Familienreisen sind hier top! Fincas, Parks und Dörfer für *Kinder*. Nennen Sie das Alter, wir organisieren Sitze, Tempo und Aktivitäten. Tippen zum Mitteilen.",
    pt:"Viajar em família é ótimo aqui! Fazendas, parques e vilarejos para *crianças*. Diga as idades e preparamos cadeirinhas, ritmo e atividades. Toque para avisar." } },
  { id:"souvenirs", action:"maps:artesanías y café souvenirs", a:{
    es:"Lleva recuerdos únicos: *café de origen*, artesanías en *guadua y bejuco*, sombreros, mochilas y chocolate. Los mejores lugares: *Salento, Filandia y Armenia*. Toca para verlos en el mapa.",
    en:"Take home unique souvenirs: *origin coffee*, *bamboo/wicker* crafts, hats, bags and chocolate. Best spots: *Salento, Filandia and Armenia*. Tap to see them on the map.",
    fr:"Souvenirs uniques : *café d'origine*, artisanat en *bambou/osier*, chapeaux, sacs, chocolat. Meilleurs endroits : *Salento, Filandia, Armenia*.",
    de:"Einzigartige Souvenirs: *Ursprungskaffee*, *Bambus/Korb*-Kunsthandwerk, Hüte, Taschen, Schokolade. Beste Orte: *Salento, Filandia, Armenia*.",
    pt:"Leve lembranças únicas: *café de origem*, artesanato em *bambu/vime*, chapéus, bolsas e chocolate. Melhores lugares: *Salento, Filandia e Armenia*." } },
  { id:"includes", action:"wa:wa_generic", a:{
    es:"Cada plan indica qué incluye (normalmente *guía, transporte, entradas y algunas comidas*). Para el detalle exacto de *tu* reserva, toca el botón y te confirmo todo al instante.",
    en:"Each plan lists what's included (usually *guide, transport, entrances and some meals*). For the exact details of *your* booking, tap the button and I'll confirm everything.",
    fr:"Chaque formule précise ce qui est inclus (*guide, transport, entrées, certains repas*). Pour le détail de *votre* réservation, touchez le bouton.",
    de:"Jedes Paket nennt die Leistungen (meist *Guide, Transport, Eintritte, einige Mahlzeiten*). Für Details *Ihrer* Buchung tippen Sie den Button.",
    pt:"Cada plano indica o que inclui (geralmente *guia, transporte, entradas e algumas refeições*). Para o detalhe da *sua* reserva, toque no botão." } },
  { id:"insurance", action:"info", a:{
    es:"Varios planes incluyen *tarjeta de asistencia médica*. Aun así, recomendamos un *seguro de viaje* personal. Revisa tu cobertura y, ante urgencia, marca *123*.",
    en:"Several plans include a *medical assistance card*. We still recommend personal *travel insurance*. Check your coverage and, in an emergency, dial *123*.",
    fr:"Plusieurs formules incluent une *carte d'assistance médicale*. Nous recommandons une *assurance voyage*. Vérifiez votre couverture ; urgence : *123*.",
    de:"Mehrere Pakete enthalten eine *medizinische Assistenzkarte*. Wir empfehlen dennoch eine *Reiseversicherung*. Prüfen Sie Ihren Schutz; Notruf *123*.",
    pt:"Vários planos incluem *cartão de assistência médica*. Ainda assim, recomendamos *seguro de viagem*. Verifique sua cobertura; emergência: *123*." } },
  { id:"vaccines", action:"info", a:{
    es:"Para el Eje Cafetero *no se exigen vacunas*. Si extiendes tu viaje a selva/Amazonía o zonas bajas, se recomienda *fiebre amarilla*. Consulta siempre a tu médico antes de viajar.",
    en:"No vaccines are *required* for the Coffee Region. If you extend to jungle/Amazon or lowlands, *yellow fever* is recommended. Always check with your doctor before travelling.",
    fr:"Aucun vaccin *exigé* pour la région du café. Pour la jungle/Amazonie ou basses terres, *fièvre jaune* recommandée. Consultez votre médecin.",
    de:"Für die Kaffeeregion sind *keine Impfungen vorgeschrieben*. Bei Dschungel/Amazonas oder Tiefland wird *Gelbfieber* empfohlen. Fragen Sie Ihren Arzt.",
    pt:"Para a Região Cafeeira *não há vacinas obrigatórias*. Se estender à selva/Amazônia ou terras baixas, *febre amarela* é recomendada. Consulte seu médico." } },
  { id:"extend", action:"wa:wa_generic", a:{
    es:"¡Me encanta! Podemos *agregar días o experiencias* — incluyendo rincones de *Colombia inexplorada* fuera de las rutas típicas. Toca el botón y te armo una propuesta a tu medida.",
    en:"Love it! We can *add days or experiences* — including corners of *unexplored Colombia* off the usual routes. Tap the button and I'll craft a tailored proposal.",
    fr:"Avec plaisir ! On peut *ajouter des jours ou des expériences* — y compris la *Colombie inexplorée*. Touchez le bouton pour une proposition sur mesure.",
    de:"Sehr gern! Wir können *Tage oder Erlebnisse hinzufügen* — auch das *unerforschte Kolumbien*. Tippen Sie den Button für ein maßgeschneidertes Angebot.",
    pt:"Adoro! Podemos *adicionar dias ou experiências* — incluindo a *Colômbia inexplorada*. Toque no botão e preparo uma proposta sob medida." } },
  { id:"feedback", action:"maps:Espontáneos Travel", a:{
    es:"¡Gracias por viajar con nosotros! 💚 Si lo disfrutaste, una *reseña* nos ayuda muchísimo a seguir creciendo. Toca para dejarla.",
    en:"Thanks for travelling with us! 💚 If you enjoyed it, a *review* helps us grow a lot. Tap to leave one.",
    fr:"Merci d'avoir voyagé avec nous ! 💚 Un *avis* nous aide beaucoup. Touchez pour le laisser.",
    de:"Danke, dass Sie mit uns gereist sind! 💚 Eine *Bewertung* hilft uns sehr. Tippen zum Hinterlassen.",
    pt:"Obrigado por viajar conosco! 💚 Uma *avaliação* nos ajuda muito. Toque para deixar." } },
  { id:"transport", action:"info", a:{
    es:"Entre pueblos puedes usar *jeeps Willys compartidos* (típicos y económicos), *buses intermunicipales* o te coordinamos *transporte privado*. En tus recorridos reservados, el transporte ya va incluido según el plan.",
    en:"Between towns use shared *Willys jeeps* (iconic and cheap), *intercity buses*, or we arrange *private transport*. On your booked tours, transport is included per the plan.",
    fr:"Entre villages : *jeeps Willys partagés*, *bus interurbains*, ou *transport privé* que nous organisons. Sur vos tours réservés, le transport est inclus.",
    de:"Zwischen Dörfern: geteilte *Willys-Jeeps*, *Überlandbusse* oder von uns organisierter *Privattransport*. Bei gebuchten Touren ist Transport inklusive.",
    pt:"Entre vilarejos: *jeeps Willys compartilhados*, *ônibus intermunicipais* ou *transporte privado* que organizamos. Nos tours reservados, o transporte já está incluído." } },
  { id:"bathrooms", action:"info", a:{
    es:"Hay baños en restaurantes, estaciones, parques y fincas. En algunos públicos cobran una pequeña suma (~1.000 COP). Lleva algo de efectivo y papel por si acaso.",
    en:"Toilets are in restaurants, stations, parks and farms. Some public ones charge a small fee (~1,000 COP). Carry some cash and tissue just in case.",
    fr:"Toilettes dans restaurants, gares, parcs et fermes. Certaines publiques sont payantes (~1 000 COP). Prévoyez un peu de liquide et des mouchoirs.",
    de:"Toiletten in Restaurants, Bahnhöfen, Parks und Fincas. Manche öffentliche kosten wenig (~1.000 COP). Etwas Bargeld und Taschentücher mitnehmen.",
    pt:"Banheiros em restaurantes, estações, parques e fazendas. Alguns públicos cobram pouco (~1.000 COP). Leve dinheiro e lenço por garantia." } },
  { id:"photography", action:"info", a:{
    es:"¡Foto libre! 📸 Para *drones* se necesitan permisos en parques, aeropuertos y zonas protegidas; pregúntanos antes de volar. Respeta a las personas y pide permiso para retratos.",
    en:"Photos are welcome! 📸 *Drones* need permits in parks, airports and protected areas; ask us before flying. Respect people and ask before portraits.",
    fr:"Photos bienvenues ! 📸 Les *drones* nécessitent des autorisations (parcs, aéroports, zones protégées) ; demandez avant. Demandez l'accord pour les portraits.",
    de:"Fotos gern! 📸 *Drohnen* brauchen Genehmigungen (Parks, Flughäfen, Schutzgebiete); fragen Sie vorher. Für Porträts um Erlaubnis bitten.",
    pt:"Fotos liberadas! 📸 *Drones* exigem permissões (parques, aeroportos, áreas protegidas); pergunte antes. Peça permissão para retratos." } },
  { id:"pets", action:"wa:wa_generic", a:{
    es:"¿Viajas con tu mascota? 🐾 Algunos lugares las permiten y otros no. Cuéntanos qué mascota y revisamos qué recorridos y hoteles son pet-friendly. Toca para avisarnos.",
    en:"Travelling with your pet? 🐾 Some places allow them, others don't. Tell us which pet and we'll check which tours and hotels are pet-friendly. Tap to let us know.",
    fr:"Vous voyagez avec votre animal ? 🐾 Dites-nous lequel et nous vérifions les tours/hôtels pet-friendly. Touchez pour nous dire.",
    de:"Mit Haustier unterwegs? 🐾 Sagen Sie uns welches, wir prüfen haustierfreundliche Touren/Hotels. Tippen zum Mitteilen.",
    pt:"Viaja com seu pet? 🐾 Diga qual e verificamos tours/hotéis pet-friendly. Toque para avisar." } },
  { id:"laundry", action:"info", a:{
    es:"Muchos hoteles ofrecen *lavandería* y hay lavanderías locales (por kilo, rápidas). Pídela en recepción o escríbenos y te indicamos una cercana.",
    en:"Many hotels offer *laundry* and there are local laundromats (by the kilo, fast). Ask at reception or message us for a nearby one.",
    fr:"Beaucoup d'hôtels proposent la *blanchisserie* ; il y a aussi des laveries locales (au kilo). Demandez à la réception ou écrivez-nous.",
    de:"Viele Hotels bieten *Wäscheservice*; es gibt lokale Wäschereien (nach Kilo). An der Rezeption fragen oder uns schreiben.",
    pt:"Muitos hotéis oferecem *lavanderia*; há lavanderias locais (por quilo). Peça na recepção ou fale conosco." } },
  { id:"cancellation", action:"wa:wa_generic", a:{
    es:"Los cambios y cancelaciones dependen del plan y la anticipación. Escríbenos tu caso y buscamos la mejor solución (reprogramar suele ser más fácil que cancelar). Toca el botón.",
    en:"Changes and cancellations depend on the plan and notice. Message us your case and we'll find the best solution (rescheduling is usually easier than cancelling). Tap the button.",
    fr:"Changements/annulations selon la formule et le délai. Écrivez-nous ; reprogrammer est souvent plus simple qu'annuler. Touchez le bouton.",
    de:"Änderungen/Stornierungen hängen vom Paket und der Vorlaufzeit ab. Schreiben Sie uns; Umbuchen ist oft einfacher. Tippen Sie den Button.",
    pt:"Mudanças/cancelamentos dependem do plano e da antecedência. Fale conosco; remarcar costuma ser mais fácil. Toque no botão." } },
  { id:"nightlife", action:"info", a:{
    es:"De noche, *Armenia y Pereira* tienen bares y zona rosa; *Salento y Filandia* son más tranquilos y encantadores. ¿Quieres una recomendación? Pregúntame o escríbele a tu anfitrión.",
    en:"At night, *Armenia and Pereira* have bars and nightlife; *Salento and Filandia* are quieter and charming. Want a recommendation? Ask me or message your host.",
    fr:"Le soir, *Armenia et Pereira* ont des bars ; *Salento et Filandia* sont plus tranquilles. Une reco ? Demandez-moi.",
    de:"Abends haben *Armenia und Pereira* Bars; *Salento und Filandia* sind ruhiger. Empfehlung? Fragen Sie mich.",
    pt:"À noite, *Armenia e Pereira* têm bares; *Salento e Filandia* são mais tranquilos. Quer indicação? Pergunte-me." } },
  { id:"holidays", action:"info", a:{
    es:"En *festivos colombianos* y temporada alta (Semana Santa, junio–julio, diciembre–enero) hay más gente y los sitios se llenan. Te recomendamos *reservar con anticipación*.",
    en:"On *Colombian holidays* and high season (Easter, June–July, December–January) it's busier and sites fill up. We recommend *booking in advance*.",
    fr:"Pendant les *jours fériés* et la haute saison (Pâques, juin–juillet, décembre–janvier), c'est plus fréquenté. Réservez *à l'avance*.",
    de:"An *Feiertagen* und in der Hochsaison (Ostern, Juni–Juli, Dezember–Januar) ist mehr los. *Frühzeitig buchen*.",
    pt:"Em *feriados* e alta temporada (Páscoa, junho–julho, dezembro–janeiro) é mais cheio. Recomendamos *reservar com antecedência*." } },
  { id:"apps", action:"info", a:{
    es:"Apps útiles: *Google Maps* o *Maps.me* (mapas sin conexión), *WhatsApp* (para nosotros), *inDrive/DiDi* (taxis), *XE* (cambio de moneda) y tu app bancaria. Descárgalas antes de salir.",
    en:"Handy apps: *Google Maps* or *Maps.me* (offline), *WhatsApp* (for us), *inDrive/DiDi* (taxis), *XE* (currency) and your banking app. Download them before you go.",
    fr:"Apps utiles : *Google Maps*/*Maps.me* (hors-ligne), *WhatsApp*, *inDrive/DiDi* (taxis), *XE* (change), votre app bancaire. Téléchargez-les avant.",
    de:"Nützliche Apps: *Google Maps*/*Maps.me* (offline), *WhatsApp*, *inDrive/DiDi* (Taxis), *XE* (Währung), Ihre Banking-App. Vorher laden.",
    pt:"Apps úteis: *Google Maps*/*Maps.me* (offline), *WhatsApp*, *inDrive/DiDi* (táxis), *XE* (câmbio), seu app bancário. Baixe antes." } },
  { id:"distances", action:"info", a:{
    es:"¡Todo queda cerca! Armenia–Pereira ~45 min, Armenia–Salento ~45 min, Salento–Valle de Cocora ~20 min, Armenia–Manizales ~2 h. Las carreteras son de montaña, con curvas.",
    en:"Everything's close! Armenia–Pereira ~45 min, Armenia–Salento ~45 min, Salento–Cocora Valley ~20 min, Armenia–Manizales ~2 h. Roads are mountainous and winding.",
    fr:"Tout est proche ! Armenia–Pereira ~45 min, Armenia–Salento ~45 min, Salento–Cocora ~20 min, Armenia–Manizales ~2 h. Routes de montagne sinueuses.",
    de:"Alles nah! Armenia–Pereira ~45 Min, Armenia–Salento ~45 Min, Salento–Cocora ~20 Min, Armenia–Manizales ~2 Std. Kurvige Bergstraßen.",
    pt:"Tudo perto! Armenia–Pereira ~45 min, Armenia–Salento ~45 min, Salento–Cocora ~20 min, Armenia–Manizales ~2 h. Estradas de montanha, sinuosas." } },
  { id:"dollars", action:"info", a:{
    es:"La moneda oficial es el *peso colombiano (COP)*. Algunos sitios turísticos aceptan USD o EUR, pero a una tasa menos favorable. Lo mejor: *cambiar a pesos* o pagar con *tarjeta*.",
    en:"The official currency is the *Colombian peso (COP)*. Some tourist spots accept USD or EUR, but at a worse rate. Best: *exchange to pesos* or pay by *card*.",
    fr:"La monnaie officielle est le *peso colombien (COP)*. Certains lieux acceptent USD/EUR à un taux moins avantageux. Mieux : *changer en pesos* ou *carte*.",
    de:"Offizielle Währung: *kolumbianischer Peso (COP)*. Manche Orte nehmen USD/EUR zu schlechterem Kurs. Besser: *in Pesos wechseln* oder *Karte*.",
    pt:"A moeda oficial é o *peso colombiano (COP)*. Alguns lugares aceitam USD/EUR a taxa pior. Melhor: *trocar para pesos* ou *cartão*." } },
  { id:"travelers", action:"info", a:{
    es:"¡Aquí cabe todo el mundo! 💚 Recibimos *familias, adultos mayores, viajeros solos, parejas y grupos/empresas*. Adaptamos el ritmo, el transporte y la accesibilidad a cada persona. Cuéntanos tu caso.",
    en:"Everyone's welcome here! 💚 We host *families, seniors, solo travellers, couples and groups/companies*. We adapt pace, transport and accessibility to each person. Tell us your case.",
    fr:"Tout le monde est bienvenu ! 💚 *Familles, seniors, voyageurs solo, couples, groupes/entreprises*. Nous adaptons rythme, transport et accessibilité.",
    de:"Alle sind willkommen! 💚 *Familien, Senioren, Alleinreisende, Paare, Gruppen/Firmen*. Wir passen Tempo, Transport und Barrierefreiheit an.",
    pt:"Todos são bem-vindos! 💚 *Famílias, idosos, viajantes solo, casais e grupos/empresas*. Adaptamos ritmo, transporte e acessibilidade." } },
  { id:"hospital", action:"info", a:{
    es:"Hay *clínicas y hospitales* en Armenia, Pereira y Manizales, y *droguerías* en los pueblos. Ante una urgencia marca *123*. Si estás en un recorrido, avisa de inmediato a tu guía o anfitrión.",
    en:"There are *clinics and hospitals* in Armenia, Pereira and Manizales, and *pharmacies* in the towns. In an emergency dial *123*. On a tour, alert your guide or host immediately.",
    fr:"*Cliniques et hôpitaux* à Armenia, Pereira, Manizales ; *pharmacies* dans les villages. Urgence : *123*. En excursion, prévenez votre guide ou hôte.",
    de:"*Kliniken und Krankenhäuser* in Armenia, Pereira, Manizales; *Apotheken* in den Orten. Notruf *123*. Auf Tour sofort Guide/Gastgeber informieren.",
    pt:"*Clínicas e hospitais* em Armenia, Pereira e Manizales; *farmácias* nos vilarejos. Emergência: *123*. Em passeio, avise seu guia ou anfitrião." } },
  { id:"locallang", action:"info", a:{
    es:"Los locales hablan *español*; en zonas turísticas algunos hablan algo de inglés. ¡Tranquil@! Tu *guía traduce* y yo te ayudo con frases básicas cuando quieras.",
    en:"Locals speak *Spanish*; in tourist areas some speak a little English. No worries — your *guide translates* and I can help with basic phrases anytime.",
    fr:"Les habitants parlent *espagnol* ; en zones touristiques, un peu d'anglais. Votre *guide traduit* et je donne des phrases de base.",
    de:"Einheimische sprechen *Spanisch*; in Touristengebieten etwas Englisch. Ihr *Guide übersetzt* und ich helfe mit Basissätzen.",
    pt:"Os locais falam *espanhol*; em áreas turísticas, um pouco de inglês. Seu *guia traduz* e eu ajudo com frases básicas." } },
  { id:"lostitem", action:"wa:wa_generic", a:{
    es:"¿Olvidaste algo? No te preocupes. Dinos *qué objeto* y *dónde* (hotel, vehículo, recorrido) y lo buscamos de inmediato. Toca el botón.",
    en:"Left something behind? Don't worry. Tell us *what* and *where* (hotel, vehicle, tour) and we'll look right away. Tap the button.",
    fr:"Vous avez oublié quelque chose ? Dites-nous *quoi* et *où* (hôtel, véhicule, tour) et nous cherchons tout de suite. Touchez le bouton.",
    de:"Etwas vergessen? Sagen Sie uns *was* und *wo* (Hotel, Fahrzeug, Tour) und wir suchen sofort. Tippen Sie den Button.",
    pt:"Esqueceu algo? Diga *o quê* e *onde* (hotel, veículo, tour) e procuramos na hora. Toque no botão." } },
  { id:"visa", action:"info", a:{
    es:"La mayoría de turistas (Europa, EE. UU., Reino Unido, Latinoamérica y muchos más) *no necesitan visa* para entrar a Colombia; recibes un sello de turismo de hasta *90 días* (prorrogable). Lleva pasaporte vigente y tiquete de salida. Verifica según tu nacionalidad en Migración Colombia.",
    en:"Most tourists (Europe, US, UK, Latin America and many more) *don't need a visa* to enter Colombia; you get a tourist stamp of up to *90 days* (extendable). Bring a valid passport and onward ticket. Check for your nationality with Migración Colombia.",
    fr:"La plupart des touristes (Europe, USA, R.-U., Amérique latine…) *n'ont pas besoin de visa* ; tampon touristique jusqu'à *90 jours* (prolongeable). Passeport valide et billet de sortie. Vérifiez selon votre nationalité.",
    de:"Die meisten Touristen (Europa, USA, UK, Lateinamerika…) *brauchen kein Visum*; Touristenstempel bis *90 Tage* (verlängerbar). Gültiger Reisepass und Weiterreiseticket. Je nach Nationalität prüfen.",
    pt:"A maioria dos turistas (Europa, EUA, Reino Unido, América Latina…) *não precisa de visto*; carimbo de turista de até *90 dias* (prorrogável). Passaporte válido e passagem de saída. Verifique conforme sua nacionalidade." } },
  { id:"food", action:"info", a:{
    es:"Prueba lo típico: *bandeja paisa*, *trucha* al ajillo (con patacón), *sancocho*, arepas, empanadas, *lechona* y mucha fruta tropical. Para el dulce: *arequipe*, obleas y panela. ¿Alergias o dieta? Dímelo y lo coordinamos.",
    en:"Try the classics: *bandeja paisa*, garlic *trout* (with patacón), *sancocho*, arepas, empanadas, *lechona* and lots of tropical fruit. Sweet tooth: *arequipe*, obleas and panela. Allergies or diet? Tell me and we'll coordinate.",
    fr:"Goûtez les classiques : *bandeja paisa*, *truite* à l'ail (avec patacón), *sancocho*, arepas, empanadas, *lechona* et fruits tropicaux. Sucré : *arequipe*, obleas. Allergies ou régime ? Dites-le-moi.",
    de:"Probieren Sie die Klassiker: *Bandeja Paisa*, Knoblauch-*Forelle* (mit Patacón), *Sancocho*, Arepas, Empanadas, *Lechona* und Tropenfrüchte. Süß: *Arequipe*, Obleas. Allergien/Diät? Sagen Sie es mir.",
    pt:"Prove os clássicos: *bandeja paisa*, *truta* ao alho (com patacón), *sancocho*, arepas, empanadas, *lechona* e frutas tropicais. Doce: *arequipe*, obleas. Alergias ou dieta? Me diga." } },
  { id:"drinks", action:"info", a:{
    es:"Para beber: por supuesto *café de origen* ☕, además *aguapanela* con queso, chocolate caliente, jugos de frutas exóticas y limonada de coco. Con alcohol: cerveza, *aguardiente* y ron colombiano (con moderación).",
    en:"To drink: of course *origin coffee* ☕, plus *aguapanela* with cheese, hot chocolate, exotic fruit juices and coconut lemonade. Alcoholic: beer, *aguardiente* and Colombian rum (in moderation).",
    fr:"À boire : bien sûr le *café d'origine* ☕, *aguapanela* au fromage, chocolat chaud, jus de fruits exotiques, limonade de coco. Alcool : bière, *aguardiente*, rhum colombien (avec modération).",
    de:"Zum Trinken: natürlich *Ursprungskaffee* ☕, *Aguapanela* mit Käse, heiße Schokolade, exotische Säfte, Kokos-Limonade. Alkohol: Bier, *Aguardiente*, kolumbianischer Rum (in Maßen).",
    pt:"Para beber: claro, *café de origem* ☕, *aguapanela* com queijo, chocolate quente, sucos de frutas exóticas e limonada de coco. Álcool: cerveja, *aguardiente* e rum colombiano (com moderação)." } },
  { id:"payment", action:"wa:wa_generic", a:{
    es:"Para reservar pagas un *anticipo del 50%* y el resto el día del tour. Métodos: *Nequi/Daviplata, transferencia/PSE, efectivo o tarjeta*, en pesos, dólares o euros. Toca el botón y te enviamos los datos de pago.",
    en:"To book you pay a *50% deposit* and the rest on the tour day. Methods: *Nequi/Daviplata, bank transfer/PSE, cash or card*, in pesos, dollars or euros. Tap the button and we'll send the payment details.",
    fr:"Pour réserver : *acompte de 50 %*, solde le jour du tour. Moyens : *Nequi/Daviplata, virement/PSE, espèces ou carte*, en pesos, dollars ou euros. Touchez le bouton pour les coordonnées de paiement.",
    de:"Zur Buchung: *50 % Anzahlung*, Rest am Tourtag. Methoden: *Nequi/Daviplata, Überweisung/PSE, Bargeld oder Karte*, in Pesos, Dollar oder Euro. Tippen Sie für die Zahlungsdaten.",
    pt:"Para reservar: *sinal de 50%*, restante no dia do tour. Métodos: *Nequi/Daviplata, transferência/PSE, dinheiro ou cartão*, em pesos, dólares ou euros. Toque para os dados de pagamento." } },
  { id:"culture", action:"info", a:{
    es:"Los colombianos somos *muy cálidos* 💚. Se saluda con «buenos días/tardes» y una sonrisa; el trato es cercano y amable. La puntualidad es flexible, pero nosotros llegamos a tiempo. Pide permiso para fotografiar personas y disfruta la conversación.",
    en:"Colombians are *very warm* 💚. Greet with «buenos días/tardes» and a smile; people are friendly and close. Punctuality is relaxed, but we arrive on time. Ask before photographing people and enjoy the chat.",
    fr:"Les Colombiens sont *très chaleureux* 💚. On salue avec « buenos días/tardes » et un sourire ; contact amical. Ponctualité souple, mais nous sommes à l'heure. Demandez avant de photographier les gens.",
    de:"Kolumbianer sind *sehr herzlich* 💚. Begrüßung mit «buenos días/tardes» und einem Lächeln; freundlicher Umgang. Pünktlichkeit locker, aber wir sind pünktlich. Vor Fotos von Personen fragen.",
    pt:"Os colombianos são *muito calorosos* 💚. Cumprimente com «buenos días/tardes» e um sorriso; trato próximo e amável. Pontualidade flexível, mas nós chegamos na hora. Peça permissão para fotografar pessoas." } },
  { id:"swimming", action:"info", a:{
    es:"Puedes nadar en las *aguas termales* (Santa Rosa, San Vicente), en *ríos* y piscinas de algunas fincas. Lleva *vestido de baño y toalla*. Te decimos dónde según tu plan y la seguridad del lugar.",
    en:"You can swim in the *hot springs* (Santa Rosa, San Vicente), in *rivers* and some farm pools. Bring a *swimsuit and towel*. We'll tell you where based on your plan and safety.",
    fr:"Baignade possible aux *sources thermales* (Santa Rosa, San Vicente), en *rivière* et piscines de certaines fermes. Apportez *maillot et serviette*. Nous indiquons où selon votre programme.",
    de:"Baden in den *Thermalquellen* (Santa Rosa, San Vicente), in *Flüssen* und Finca-Pools. *Badesachen und Handtuch* mitbringen. Wir sagen Ihnen wo, je nach Programm.",
    pt:"Dá para nadar nas *águas termais* (Santa Rosa, San Vicente), em *rios* e piscinas de algumas fazendas. Leve *roupa de banho e toalha*. Indicamos onde conforme seu plano." } },
  { id:"rain", action:"info", a:{
    es:"Si llueve, ¡no pasa nada! El clima cambia rápido y suele despejar. Tenemos *plan B* con actividades bajo techo (museos del café, talleres, cafés, termales). Trae *impermeable* y seguimos disfrutando. ☔",
    en:"If it rains, no problem! Weather changes fast and usually clears. We have a *plan B* with indoor activities (coffee museums, workshops, cafés, hot springs). Bring a *rain jacket* and we keep enjoying. ☔",
    fr:"S'il pleut, pas de souci ! Le temps change vite. Nous avons un *plan B* en intérieur (musées du café, ateliers, cafés, thermes). Prenez un *imperméable*. ☔",
    de:"Bei Regen kein Problem! Das Wetter wechselt schnell. Wir haben einen *Plan B* drinnen (Kaffeemuseen, Workshops, Cafés, Thermen). *Regenjacke* mitbringen. ☔",
    pt:"Se chover, tranquilo! O tempo muda rápido. Temos um *plano B* coberto (museus do café, oficinas, cafés, termas). Traga *capa de chuva*. ☔" } },
  { id:"coffee", action:"info", a:{
    es:"El café es el alma de esta tierra ☕. Vive un *tour de finca* (de la semilla a la taza) con cata de café de especialidad, y llévate café de origen recién tostado como recuerdo. ¿Quieres añadir una cata o visita? Lo coordino.",
    en:"Coffee is the soul of this land ☕. Live a *farm tour* (seed to cup) with a specialty cupping, and take home freshly roasted origin coffee. Want to add a tasting or visit? I'll arrange it.",
    fr:"Le café est l'âme de cette terre ☕. Vivez un *tour de ferme* (de la graine à la tasse) avec dégustation, et rapportez du café d'origine fraîchement torréfié. Ajouter une dégustation ? Je m'en occupe.",
    de:"Kaffee ist die Seele dieses Landes ☕. Erleben Sie eine *Finca-Tour* (vom Samen zur Tasse) mit Verkostung und nehmen Sie frisch gerösteten Ursprungskaffee mit. Verkostung hinzufügen? Ich organisiere es.",
    pt:"O café é a alma desta terra ☕. Viva um *tour de fazenda* (da semente à xícara) com degustação e leve café de origem recém-torrado. Quer adicionar uma degustação? Eu organizo." } },
  { id:"alcohol", action:"info", a:{
    es:"La edad legal para alcohol es *18 años*. Encuentras cerveza, aguardiente y ron en tiendas y bares. Disfruta con moderación, sobre todo en altura. No conduzcas si bebes; pide un taxi/app.",
    en:"The legal drinking age is *18*. Beer, aguardiente and rum are sold in shops and bars. Enjoy in moderation, especially at altitude. Don't drink and drive; use a taxi/app.",
    fr:"L'âge légal pour l'alcool est *18 ans*. Bière, aguardiente et rhum en magasins et bars. À consommer avec modération, surtout en altitude. Ne conduisez pas ; prenez un taxi/app.",
    de:"Das Mindestalter für Alkohol ist *18*. Bier, Aguardiente und Rum in Läden/Bars. In Maßen genießen, besonders in der Höhe. Nicht fahren; Taxi/App nehmen.",
    pt:"A idade legal para álcool é *18 anos*. Cerveja, aguardiente e rum em lojas e bares. Com moderação, sobretudo na altitude. Não dirija; use táxi/app." } },
  { id:"lgbt", action:"info", a:{
    es:"Eres bienvenid@ tal como eres 🏳️‍🌈. La región es *amable y tranquila*; en las ciudades hay ambiente diverso. Con respeto mutuo disfrutarás sin problema. Si tienes alguna preferencia para tu plan, cuéntanos.",
    en:"You're welcome exactly as you are 🏳️‍🌈. The region is *friendly and relaxed*; cities have a diverse scene. With mutual respect you'll enjoy without issues. Any preference for your plan? Tell us.",
    fr:"Vous êtes bienvenu·e tel·le que vous êtes 🏳️‍🌈. La région est *accueillante et tranquille* ; les villes ont une scène diverse. Avec respect mutuel, tout se passe bien. Une préférence ? Dites-nous.",
    de:"Sie sind willkommen, genau wie Sie sind 🏳️‍🌈. Die Region ist *freundlich und entspannt*; Städte haben eine diverse Szene. Mit gegenseitigem Respekt genießen Sie ohne Probleme. Wünsche? Sagen Sie es uns.",
    pt:"Você é bem-vind@ exatamente como é 🏳️‍🌈. A região é *acolhedora e tranquila*; as cidades têm cena diversa. Com respeito mútuo, você aproveita sem problemas. Alguma preferência? Conte-nos." } },
  { id:"duration", action:"info", a:{
    es:"Tenemos experiencias de *medio día, día completo y planes de varios días*. La mayoría de tours de un día duran 6–9 horas. En tu itinerario ves los horarios exactos; ¿quieres algo más corto o más largo? Lo ajustamos.",
    en:"We have *half-day, full-day and multi-day* experiences. Most day tours last 6–9 hours. Your itinerary shows the exact times; want something shorter or longer? We'll adjust.",
    fr:"Nous avons des expériences de *demi-journée, journée entière et plusieurs jours*. La plupart des tours d'une journée durent 6–9 h. Votre itinéraire indique les horaires ; plus court ou plus long ? On ajuste.",
    de:"Wir haben *Halbtags-, Ganztags- und Mehrtageserlebnisse*. Die meisten Tagestouren dauern 6–9 Std. Ihr Programm zeigt die Zeiten; kürzer oder länger? Wir passen an.",
    pt:"Temos experiências de *meio dia, dia inteiro e vários dias*. A maioria dos tours de um dia dura 6–9 horas. Seu itinerário mostra os horários; quer mais curto ou mais longo? Ajustamos." } },
  { id:"privatetours", action:"wa:wa_generic", a:{
    es:"Ofrecemos tours *privados* (solo tu grupo, a tu ritmo) y *compartidos* (más económicos). También armamos *planes a la medida* y para *grupos o empresas*. Toca el botón y te cotizamos el formato que prefieras.",
    en:"We offer *private* tours (just your group, your pace) and *shared* ones (cheaper). We also build *custom plans* and options for *groups or companies*. Tap the button for a quote in your preferred format.",
    fr:"Nous proposons des tours *privés* (votre groupe, votre rythme) et *partagés* (moins chers). Aussi des *plans sur mesure* et pour *groupes/entreprises*. Touchez le bouton pour un devis.",
    de:"Wir bieten *private* Touren (nur Ihre Gruppe, Ihr Tempo) und *geteilte* (günstiger). Auch *maßgeschneiderte Pläne* und für *Gruppen/Firmen*. Tippen Sie für ein Angebot.",
    pt:"Oferecemos tours *privativos* (só seu grupo, seu ritmo) e *compartilhados* (mais baratos). Também *planos sob medida* e para *grupos/empresas*. Toque para cotar." } },
  { id:"flightdelay", action:"wa:wa_generic", a:{
    es:"¿Tu vuelo se retrasó o cambió? No te preocupes — avísanos cuanto antes por WhatsApp y *reprogramamos tu recogida* y tu itinerario sin estrés. Toca el botón.",
    en:"Flight delayed or changed? Don't worry — let us know ASAP on WhatsApp and we'll *reschedule your pickup* and itinerary stress-free. Tap the button.",
    fr:"Vol retardé ou modifié ? Pas de souci — prévenez-nous vite sur WhatsApp et nous *reprogrammons votre prise en charge* et votre itinéraire. Touchez le bouton.",
    de:"Flug verspätet/geändert? Keine Sorge — melden Sie sich schnell per WhatsApp und wir *verschieben Ihre Abholung* und das Programm. Tippen Sie den Button.",
    pt:"Voo atrasou ou mudou? Tranquilo — avise-nos logo no WhatsApp e *remarcamos sua retirada* e o itinerário. Toque no botão." } }
];
