/* ==========================================================================
   Espontáneos Travel — Conserje "Espo": base de conocimiento (ES/EN/FR/DE/PT)
   + strings de interfaz. Zero-cost, estático. Editable y expandible (IA luego).
   Placeholders que rellena concierge.js: {name} {region} {guide} {guideLangs}
   {host} {hotel} {hotelArea}
   ========================================================================== */

const CUI = {
  es: {
    brand: "Conserje de viaje", sub: "Espontáneos Travel",
    greet: "¡Hola {name}! 👋 Soy Espo, tu anfitrión digital durante tu viaje por {region}. Estoy aquí 24/7. ¿En qué te ayudo?",
    menu_prompt: "Elige un tema o escríbenos:",
    next_stop: "Tu próxima parada", itinerary: "Tu itinerario", trip_done: "¡Tu viaje está completo! Gracias por viajar con nosotros 💚",
    status: "Reserva", party: "Viajeros", guide: "Tu guía", hotel: "Tu hotel", today: "Hoy", tomorrow: "Mañana",
    enter_code: "Ingresa tu código de reserva", go: "Entrar", not_found: "No encontramos esa reserva. Revisa el código o escríbenos por WhatsApp.",
    back: "↩ Menú", wa_host: "Escribir a mi anfitrión", call_host: "Llamar al anfitrión", call_driver: "Llamar al conductor",
    maps_btn: "Abrir en el mapa", foot: "Respuestas guiadas · tu anfitrión confirma los detalles",
    wa_open: "Abrir WhatsApp", more: "¿Algo más? Elige otra opción 👇",
    m_schedule: "🗓️ Mis horarios", m_change: "⏰ Cambiar un horario", m_taxi: "🚕 Pedir taxi", m_lost: "🧭 Estoy lejos / perdido",
    m_restaurants: "🍽️ Restaurantes", m_money: "💱 Dinero / cambio", m_weather: "🌤️ Clima", m_clothing: "🧥 Qué ropa",
    m_diet: "🥗 Comida / dieta", m_access: "♿ Accesibilidad", m_health: "💊 Salud / medicamentos", m_wifi: "📶 Wifi / señal",
    m_guide: "🧑‍🏫 Mi guía", m_pack: "🎒 Qué llevar", m_tips: "💵 Propinas", m_phrases: "🗣️ Frases en español",
    m_reco: "⭐ Recomendaciones", m_emergency: "🚨 Emergencias", m_host: "💬 Hablar con mi anfitrión",
    wa_change: "Hola, soy {name} (reserva {code}). Quiero *cambiar un horario* de mi itinerario:",
    wa_taxi: "Hola, soy {name} (reserva {code}). ¿Me ayudan a *pedir un taxi*? Estoy en:",
    wa_lost: "Hola, soy {name} (reserva {code}). *Necesito ayuda para ubicarme.* Mi ubicación:",
    wa_access: "Hola, soy {name} (reserva {code}). Necesito *apoyo de accesibilidad* (silla de ruedas / coche para bebé / otro):",
    wa_generic: "Hola, soy {name} (reserva {code}). Tengo una consulta:"
  },
  en: {
    brand: "Travel concierge", sub: "Espontáneos Travel",
    greet: "Hi {name}! 👋 I'm Espo, your digital host during your trip around {region}. I'm here 24/7. How can I help?",
    menu_prompt: "Pick a topic or message us:",
    next_stop: "Your next stop", itinerary: "Your itinerary", trip_done: "Your trip is complete! Thanks for travelling with us 💚",
    status: "Booking", party: "Travellers", guide: "Your guide", hotel: "Your hotel", today: "Today", tomorrow: "Tomorrow",
    enter_code: "Enter your booking code", go: "Enter", not_found: "We couldn't find that booking. Check the code or message us on WhatsApp.",
    back: "↩ Menu", wa_host: "Message my host", call_host: "Call the host", call_driver: "Call the driver",
    maps_btn: "Open in maps", foot: "Guided answers · your host confirms the details",
    wa_open: "Open WhatsApp", more: "Anything else? Pick another option 👇",
    m_schedule: "🗓️ My schedule", m_change: "⏰ Change a time", m_taxi: "🚕 Get a taxi", m_lost: "🧭 I'm far / lost",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Money / exchange", m_weather: "🌤️ Weather", m_clothing: "🧥 What to wear",
    m_diet: "🥗 Food / diet", m_access: "♿ Accessibility", m_health: "💊 Health / meds", m_wifi: "📶 Wi-Fi / signal",
    m_guide: "🧑‍🏫 My guide", m_pack: "🎒 What to pack", m_tips: "💵 Tipping", m_phrases: "🗣️ Spanish phrases",
    m_reco: "⭐ Recommendations", m_emergency: "🚨 Emergencies", m_host: "💬 Talk to my host",
    wa_change: "Hi, I'm {name} (booking {code}). I'd like to *change a time* in my itinerary:",
    wa_taxi: "Hi, I'm {name} (booking {code}). Can you help me *get a taxi*? I'm at:",
    wa_lost: "Hi, I'm {name} (booking {code}). *I need help finding my way.* My location:",
    wa_access: "Hi, I'm {name} (booking {code}). I need *accessibility support* (wheelchair / baby seat / other):",
    wa_generic: "Hi, I'm {name} (booking {code}). I have a question:"
  },
  fr: {
    brand: "Conciergerie de voyage", sub: "Espontáneos Travel",
    greet: "Bonjour {name} ! 👋 Je suis Espo, votre hôte numérique pendant votre voyage dans {region}. Disponible 24/7. Comment aider ?",
    menu_prompt: "Choisissez un thème ou écrivez-nous :",
    next_stop: "Votre prochaine étape", itinerary: "Votre itinéraire", trip_done: "Votre voyage est terminé ! Merci d'avoir voyagé avec nous 💚",
    status: "Réservation", party: "Voyageurs", guide: "Votre guide", hotel: "Votre hôtel", today: "Aujourd'hui", tomorrow: "Demain",
    enter_code: "Saisissez votre code de réservation", go: "Entrer", not_found: "Réservation introuvable. Vérifiez le code ou écrivez-nous sur WhatsApp.",
    back: "↩ Menu", wa_host: "Écrire à mon hôte", call_host: "Appeler l'hôte", call_driver: "Appeler le chauffeur",
    maps_btn: "Ouvrir la carte", foot: "Réponses guidées · votre hôte confirme les détails",
    wa_open: "Ouvrir WhatsApp", more: "Autre chose ? Choisissez 👇",
    m_schedule: "🗓️ Mes horaires", m_change: "⏰ Changer un horaire", m_taxi: "🚕 Un taxi", m_lost: "🧭 Je suis loin / perdu",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Argent / change", m_weather: "🌤️ Météo", m_clothing: "🧥 Quoi porter",
    m_diet: "🥗 Repas / régime", m_access: "♿ Accessibilité", m_health: "💊 Santé / médicaments", m_wifi: "📶 Wi-Fi / réseau",
    m_guide: "🧑‍🏫 Mon guide", m_pack: "🎒 À emporter", m_tips: "💵 Pourboires", m_phrases: "🗣️ Phrases en espagnol",
    m_reco: "⭐ Recommandations", m_emergency: "🚨 Urgences", m_host: "💬 Parler à mon hôte",
    wa_change: "Bonjour, je suis {name} (réservation {code}). Je souhaite *changer un horaire* :",
    wa_taxi: "Bonjour, je suis {name} (réservation {code}). Pouvez-vous m'aider à *trouver un taxi* ? Je suis à :",
    wa_lost: "Bonjour, je suis {name} (réservation {code}). *J'ai besoin d'aide pour m'orienter.* Ma position :",
    wa_access: "Bonjour, je suis {name} (réservation {code}). J'ai besoin d'un *soutien d'accessibilité* (fauteuil / siège bébé / autre) :",
    wa_generic: "Bonjour, je suis {name} (réservation {code}). J'ai une question :"
  },
  de: {
    brand: "Reise-Concierge", sub: "Espontáneos Travel",
    greet: "Hallo {name}! 👋 Ich bin Espo, Ihr digitaler Gastgeber während Ihrer Reise durch {region}. 24/7 für Sie da. Wie kann ich helfen?",
    menu_prompt: "Wählen Sie ein Thema oder schreiben Sie uns:",
    next_stop: "Ihr nächster Halt", itinerary: "Ihr Programm", trip_done: "Ihre Reise ist abgeschlossen! Danke, dass Sie mit uns gereist sind 💚",
    status: "Buchung", party: "Reisende", guide: "Ihr Guide", hotel: "Ihr Hotel", today: "Heute", tomorrow: "Morgen",
    enter_code: "Buchungscode eingeben", go: "Los", not_found: "Buchung nicht gefunden. Prüfen Sie den Code oder schreiben Sie uns per WhatsApp.",
    back: "↩ Menü", wa_host: "Gastgeber schreiben", call_host: "Gastgeber anrufen", call_driver: "Fahrer anrufen",
    maps_btn: "In Karte öffnen", foot: "Geführte Antworten · Ihr Gastgeber bestätigt die Details",
    wa_open: "WhatsApp öffnen", more: "Noch etwas? Wählen Sie 👇",
    m_schedule: "🗓️ Meine Zeiten", m_change: "⏰ Zeit ändern", m_taxi: "🚕 Taxi", m_lost: "🧭 Weit weg / verirrt",
    m_restaurants: "🍽️ Restaurants", m_money: "💱 Geld / Wechsel", m_weather: "🌤️ Wetter", m_clothing: "🧥 Kleidung",
    m_diet: "🥗 Essen / Diät", m_access: "♿ Barrierefreiheit", m_health: "💊 Gesundheit / Medikamente", m_wifi: "📶 WLAN / Signal",
    m_guide: "🧑‍🏫 Mein Guide", m_pack: "🎒 Packliste", m_tips: "💵 Trinkgeld", m_phrases: "🗣️ Sätze auf Spanisch",
    m_reco: "⭐ Empfehlungen", m_emergency: "🚨 Notfälle", m_host: "💬 Mit Gastgeber sprechen",
    wa_change: "Hallo, ich bin {name} (Buchung {code}). Ich möchte eine *Uhrzeit ändern*:",
    wa_taxi: "Hallo, ich bin {name} (Buchung {code}). Können Sie mir ein *Taxi besorgen*? Ich bin bei:",
    wa_lost: "Hallo, ich bin {name} (Buchung {code}). *Ich brauche Hilfe bei der Orientierung.* Mein Standort:",
    wa_access: "Hallo, ich bin {name} (Buchung {code}). Ich brauche *Barrierefreiheits-Unterstützung* (Rollstuhl / Babysitz / anderes):",
    wa_generic: "Hallo, ich bin {name} (Buchung {code}). Ich habe eine Frage:"
  },
  pt: {
    brand: "Concierge de viagem", sub: "Espontáneos Travel",
    greet: "Olá {name}! 👋 Sou o Espo, seu anfitrião digital durante sua viagem por {region}. Estou aqui 24/7. Como posso ajudar?",
    menu_prompt: "Escolha um tema ou escreva:",
    next_stop: "Sua próxima parada", itinerary: "Seu itinerário", trip_done: "Sua viagem está completa! Obrigado por viajar conosco 💚",
    status: "Reserva", party: "Viajantes", guide: "Seu guia", hotel: "Seu hotel", today: "Hoje", tomorrow: "Amanhã",
    enter_code: "Digite seu código de reserva", go: "Entrar", not_found: "Reserva não encontrada. Verifique o código ou fale conosco no WhatsApp.",
    back: "↩ Menu", wa_host: "Falar com meu anfitrião", call_host: "Ligar para o anfitrião", call_driver: "Ligar para o motorista",
    maps_btn: "Abrir no mapa", foot: "Respostas guiadas · seu anfitrião confirma os detalhes",
    wa_open: "Abrir WhatsApp", more: "Mais alguma coisa? Escolha 👇",
    m_schedule: "🗓️ Meus horários", m_change: "⏰ Mudar um horário", m_taxi: "🚕 Pedir táxi", m_lost: "🧭 Estou longe / perdido",
    m_restaurants: "🍽️ Restaurantes", m_money: "💱 Dinheiro / câmbio", m_weather: "🌤️ Clima", m_clothing: "🧥 O que vestir",
    m_diet: "🥗 Comida / dieta", m_access: "♿ Acessibilidade", m_health: "💊 Saúde / remédios", m_wifi: "📶 Wi-Fi / sinal",
    m_guide: "🧑‍🏫 Meu guia", m_pack: "🎒 O que levar", m_tips: "💵 Gorjetas", m_phrases: "🗣️ Frases em espanhol",
    m_reco: "⭐ Recomendações", m_emergency: "🚨 Emergências", m_host: "💬 Falar com meu anfitrião",
    wa_change: "Olá, sou {name} (reserva {code}). Quero *mudar um horário* do meu itinerário:",
    wa_taxi: "Olá, sou {name} (reserva {code}). Podem me ajudar a *pedir um táxi*? Estou em:",
    wa_lost: "Olá, sou {name} (reserva {code}). *Preciso de ajuda para me localizar.* Minha localização:",
    wa_access: "Olá, sou {name} (reserva {code}). Preciso de *apoio de acessibilidade* (cadeira de rodas / bebê conforto / outro):",
    wa_generic: "Olá, sou {name} (reserva {code}). Tenho uma dúvida:"
  }
};

/* Knowledge base: each topic has a menu key (maps to CUI m_*), an action type and a 5-lang answer.
   action: "info" | "wa:<waKey>" | "dyn:<name>" (handled in concierge.js) */
const CKB = [
  { id:"schedule", menu:"m_schedule", action:"dyn:schedule" },
  { id:"guide",    menu:"m_guide",    action:"dyn:guide" },
  { id:"change",   menu:"m_change",   action:"wa:wa_change",
    a:{ es:"Dime qué parada u hora quieres mover y a qué horario. Al confirmar, *avisamos al conductor/guía que te recoge* para que todo coincida. Toca el botón y lo gestionamos por WhatsApp.",
        en:"Tell me which stop or time you want to move and to when. Once confirmed, *we notify the driver/guide picking you up* so everything matches. Tap the button and we handle it on WhatsApp.",
        fr:"Dites-moi quelle étape ou heure déplacer et à quand. Après confirmation, *nous prévenons le chauffeur/guide* qui vous récupère. Touchez le bouton, on gère sur WhatsApp.",
        de:"Sagen Sie, welchen Halt/welche Zeit Sie verschieben möchten. Nach Bestätigung *informieren wir Fahrer/Guide*, der Sie abholt. Tippen Sie, wir regeln es per WhatsApp.",
        pt:"Diga qual parada ou horário mover e para quando. Após confirmar, *avisamos o motorista/guia* que te busca. Toque no botão e resolvemos no WhatsApp." } },
  { id:"taxi", menu:"m_taxi", action:"wa:wa_taxi",
    a:{ es:"En el Eje Cafetero funcionan taxis y apps como *inDrive, DiDi y Cabify*. Para seguridad y mejor precio, *tu anfitrión puede pedírtelo*: toca el botón, dinos dónde estás y te coordinamos uno.",
        en:"In the Coffee Region there are taxis and apps like *inDrive, DiDi and Cabify*. For safety and a better price, *your host can arrange one*: tap the button, tell us where you are and we'll sort it.",
        fr:"Dans la région du café il y a des taxis et apps comme *inDrive, DiDi, Cabify*. Pour la sécurité, *votre hôte peut en commander un* : touchez le bouton et indiquez où vous êtes.",
        de:"In der Kaffeeregion gibt es Taxis und Apps wie *inDrive, DiDi, Cabify*. Für Sicherheit *kann Ihr Gastgeber eines bestellen*: Tippen Sie und sagen Sie, wo Sie sind.",
        pt:"Na Região Cafeeira há táxis e apps como *inDrive, DiDi e Cabify*. Para segurança, *seu anfitrião pode pedir um*: toque no botão e diga onde está." } },
  { id:"lost", menu:"m_lost", action:"wa:wa_lost",
    a:{ es:"Tranquil@. Toca el botón, *comparte tu ubicación en WhatsApp* (clip 📎 → Ubicación → Ubicación actual) y te guiamos o enviamos a alguien. Si es urgente, llama a tu anfitrión.",
        en:"Don't worry. Tap the button, *share your location on WhatsApp* (clip 📎 → Location → Current location) and we'll guide you or send someone. If urgent, call your host.",
        fr:"Pas d'inquiétude. Touchez le bouton, *partagez votre position sur WhatsApp* (📎 → Position) et on vous guide. Si urgent, appelez votre hôte.",
        de:"Keine Sorge. Tippen Sie, *teilen Sie Ihren Standort auf WhatsApp* (📎 → Standort) und wir leiten Sie. Bei Dringlichkeit rufen Sie Ihren Gastgeber an.",
        pt:"Calma. Toque no botão, *compartilhe sua localização no WhatsApp* (📎 → Localização) e te guiamos. Se urgente, ligue para seu anfitrião." } },
  { id:"restaurants", menu:"m_restaurants", action:"maps:restaurants",
    a:{ es:"Cerca encuentras cocina típica (trucha, patacón, bandeja paisa) y cafés de especialidad. Toca para ver *restaurantes locales en el mapa*. ¿Quieres una recomendación según tu zona o dieta? Pregúntame.",
        en:"Nearby you'll find typical food (trout, patacón, bandeja paisa) and specialty coffee. Tap to see *local restaurants on the map*. Want a pick by area or diet? Just ask.",
        fr:"À proximité : cuisine typique (truite, patacón, bandeja paisa) et cafés de spécialité. Touchez pour voir *les restaurants sur la carte*. Une reco selon votre régime ? Demandez.",
        de:"In der Nähe: typische Küche (Forelle, Patacón, Bandeja Paisa) und Spezialitätenkaffee. Tippen für *Restaurants auf der Karte*. Empfehlung nach Diät? Fragen Sie.",
        pt:"Por perto: comida típica (truta, patacón, bandeja paisa) e cafés especiais. Toque para ver *restaurantes no mapa*. Quer uma indicação por dieta? É só pedir." } },
  { id:"money", menu:"m_money", action:"maps:casa de cambio",
    a:{ es:"La moneda es el *peso colombiano (COP)*. Se paga con tarjeta en hoteles y muchos sitios; lleva *efectivo* para pueblos y propinas. Hay cajeros y casas de cambio en Armenia, Pereira y Manizales. Toca para verlas en el mapa.",
        en:"The currency is the *Colombian peso (COP)*. Cards work in hotels and many places; carry *cash* for villages and tips. ATMs and exchange offices are in Armenia, Pereira and Manizales. Tap to see them on the map.",
        fr:"La monnaie est le *peso colombien (COP)*. Carte acceptée dans les hôtels ; prévoyez du *liquide* pour les villages et pourboires. Distributeurs et bureaux de change à Armenia, Pereira, Manizales.",
        de:"Währung ist der *kolumbianische Peso (COP)*. Karte in Hotels ok; *Bargeld* für Dörfer und Trinkgeld mitnehmen. Geldautomaten/Wechselstuben in Armenia, Pereira, Manizales.",
        pt:"A moeda é o *peso colombiano (COP)*. Cartão em hotéis e muitos lugares; leve *dinheiro* para vilarejos e gorjetas. Caixas e câmbios em Armenia, Pereira e Manizales." } },
  { id:"weather", menu:"m_weather", action:"info",
    a:{ es:"El Eje Cafetero es *primavera todo el año*: 18–26 °C de día, fresco en la noche y en zonas altas (Cocora, páramo). Llueve a ratos casi cualquier día. Revisa el clima del día en tu app del celular. ☀️🌧️",
        en:"The Coffee Region is *spring-like all year*: 18–26 °C by day, cool at night and in high areas (Cocora, páramo). Brief rain can happen any day. Check today's forecast on your phone. ☀️🌧️",
        fr:"La région du café, c'est le *printemps toute l'année* : 18–26 °C le jour, frais la nuit et en altitude (Cocora, páramo). Pluie brève possible. Vérifiez la météo sur votre téléphone. ☀️🌧️",
        de:"Die Kaffeeregion ist *ganzjährig frühlingshaft*: tagsüber 18–26 °C, nachts/in Höhen (Cocora, Páramo) kühl. Kurzer Regen jederzeit möglich. Wetter per Handy prüfen. ☀️🌧️",
        pt:"A Região Cafeeira é *primavera o ano todo*: 18–26 °C de dia, fresco à noite e em zonas altas (Cocora, páramo). Pode chover rápido. Veja a previsão no celular. ☀️🌧️" } },
  { id:"clothing", menu:"m_clothing", action:"info",
    a:{ es:"Lleva *ropa en capas*: camiseta + chaqueta liviana o impermeable, *zapatos cómodos/cerrados* para caminar, gorra, bloqueador y repelente. Para Cocora o páramo, abrígate más. 🥾🧥",
        en:"Dress in *layers*: t-shirt + light or waterproof jacket, *comfy closed shoes* for walking, cap, sunscreen and repellent. For Cocora or páramo, bring warmer layers. 🥾🧥",
        fr:"Habillez-vous *en couches* : t-shirt + veste légère/imperméable, *chaussures fermées confortables*, casquette, crème solaire, répulsif. Pour Cocora/páramo, plus chaud. 🥾🧥",
        de:"Kleidung im *Zwiebellook*: T-Shirt + leichte/wasserdichte Jacke, *bequeme geschlossene Schuhe*, Kappe, Sonnencreme, Mückenschutz. Für Cocora/Páramo wärmer. 🥾🧥",
        pt:"Use *camadas*: camiseta + jaqueta leve/impermeável, *calçado fechado confortável*, boné, protetor solar e repelente. Para Cocora/páramo, leve mais agasalho. 🥾🧥" } },
  { id:"diet", menu:"m_diet", action:"wa:wa_generic",
    a:{ es:"Hay opciones *vegetarianas, veganas y sin gluten* con aviso previo. Si tienes *alergias* o preferencias, cuéntanos y lo coordinamos con los restaurantes y fincas. Toca para avisarnos.",
        en:"There are *vegetarian, vegan and gluten-free* options with notice. If you have *allergies* or preferences, tell us and we'll coordinate with restaurants and farms. Tap to let us know.",
        fr:"Options *végétariennes, véganes et sans gluten* sur demande. *Allergies* ou préférences ? Dites-le, on coordonne avec restaurants et fermes. Touchez pour nous informer.",
        de:"*Vegetarische, vegane und glutenfreie* Optionen auf Vorbestellung. *Allergien*/Wünsche? Sagen Sie Bescheid, wir stimmen uns mit Restaurants/Fincas ab. Tippen zum Melden.",
        pt:"Há opções *vegetarianas, veganas e sem glúten* com aviso. *Alergias* ou preferências? Conte e coordenamos com restaurantes e fazendas. Toque para avisar." } },
  { id:"access", menu:"m_access", action:"wa:wa_access",
    a:{ es:"Creemos en el *turismo sin barreras* ♿. Según el recorrido coordinamos *silla de ruedas, coche para bebé, rutas y transporte accesibles y apoyo personal*. Cuéntanos qué necesitas y lo preparamos. Toca el botón.",
        en:"We believe in *barrier-free tourism* ♿. Depending on the tour we arrange *wheelchair, baby seat, accessible routes/transport and personal support*. Tell us what you need and we'll prepare it. Tap the button.",
        fr:"Nous croyons au *tourisme sans barrières* ♿. Selon l'excursion : *fauteuil, siège bébé, itinéraires/transport accessibles et accompagnement*. Dites vos besoins. Touchez le bouton.",
        de:"Wir glauben an *barrierefreien Tourismus* ♿. Je nach Tour organisieren wir *Rollstuhl, Babysitz, barrierefreie Wege/Transport und Begleitung*. Sagen Sie uns Ihren Bedarf. Tippen.",
        pt:"Acreditamos no *turismo sem barreiras* ♿. Conforme o passeio: *cadeira de rodas, bebê conforto, rotas/transporte acessíveis e apoio pessoal*. Diga o que precisa. Toque no botão." } },
  { id:"health", menu:"m_health", action:"info",
    a:{ es:"Recorridos suaves (fincas, pueblos, termales) son aptos para casi todos. Caminatas (Cocora, páramo) piden *condición física media* y hay *altura* (hasta ~3.000 m). Lleva tus *medicamentos personales*, hidratación y, si tienes una condición, avísanos para adaptar el ritmo. No somos servicio médico; ante emergencia, 123.",
        en:"Easy tours (farms, towns, hot springs) suit almost everyone. Hikes (Cocora, páramo) need *moderate fitness* and involve *altitude* (up to ~3,000 m). Bring your *personal meds*, stay hydrated and, if you have a condition, tell us to adapt the pace. We're not a medical service; in an emergency, dial 123.",
        fr:"Excursions faciles (fermes, villages, thermes) pour presque tous. Randos (Cocora, páramo) : *condition moyenne* et *altitude* (~3 000 m). Prenez vos *médicaments*, hydratez-vous ; une condition ? Prévenez-nous. Pas un service médical ; urgence : 123.",
        de:"Leichte Touren (Fincas, Dörfer, Thermen) für fast alle. Wanderungen (Cocora, Páramo): *mittlere Fitness* und *Höhe* (~3.000 m). *Eigene Medikamente* mitnehmen, trinken; bei Vorerkrankung Bescheid geben. Kein medizinischer Dienst; Notruf 123.",
        pt:"Passeios leves (fazendas, vilarejos, termas) servem a quase todos. Trilhas (Cocora, páramo): *preparo médio* e *altitude* (~3.000 m). Leve seus *remédios*, hidrate-se; se tiver condição, avise para adaptar o ritmo. Não somos serviço médico; emergência: 123." } },
  { id:"wifi", menu:"m_wifi", action:"info",
    a:{ es:"Hoteles y cafés tienen *wifi*. En fincas y zonas rurales la señal puede ser *limitada* (Claro suele tener mejor cobertura). Descarga mapas sin conexión y guarda este enlace. Tu anfitrión siempre está por WhatsApp.",
        en:"Hotels and cafés have *Wi-Fi*. On farms and rural areas signal can be *limited* (Claro tends to have better coverage). Download offline maps and save this link. Your host is always on WhatsApp.",
        fr:"Hôtels et cafés ont le *Wi-Fi*. Dans les fermes/zones rurales, le réseau peut être *limité* (Claro = meilleure couverture). Téléchargez des cartes hors-ligne. Votre hôte reste sur WhatsApp.",
        de:"Hotels/Cafés haben *WLAN*. Auf Fincas/ländlich kann das Signal *begrenzt* sein (Claro meist beste Abdeckung). Offline-Karten laden. Ihr Gastgeber ist immer per WhatsApp da.",
        pt:"Hotéis e cafés têm *Wi-Fi*. Em fazendas e zonas rurais o sinal pode ser *limitado* (Claro costuma ter melhor cobertura). Baixe mapas offline. Seu anfitrião está sempre no WhatsApp." } },
  { id:"pack", menu:"m_pack", action:"info",
    a:{ es:"Checklist 🎒: documento/pasaporte, efectivo (COP) y tarjeta, medicamentos, bloqueador y repelente, gorra/gafas, impermeable, zapatos cómodos, botella de agua, cargador/power bank y cámara. Para termales: *vestido de baño y toalla*.",
        en:"Checklist 🎒: ID/passport, cash (COP) and card, meds, sunscreen and repellent, cap/sunglasses, rain jacket, comfy shoes, water bottle, charger/power bank and camera. For hot springs: *swimsuit and towel*.",
        fr:"Checklist 🎒 : pièce d'identité, liquide (COP) et carte, médicaments, crème solaire, répulsif, casquette/lunettes, imperméable, chaussures confortables, gourde, chargeur et appareil photo. Thermes : *maillot et serviette*.",
        de:"Checkliste 🎒: Ausweis/Pass, Bargeld (COP) und Karte, Medikamente, Sonnencreme, Mückenschutz, Kappe/Brille, Regenjacke, bequeme Schuhe, Trinkflasche, Ladegerät/Powerbank, Kamera. Thermen: *Badesachen und Handtuch*.",
        pt:"Checklist 🎒: documento/passaporte, dinheiro (COP) e cartão, remédios, protetor e repelente, boné/óculos, capa de chuva, calçado confortável, garrafa de água, carregador/power bank e câmera. Termas: *roupa de banho e toalha*." } },
  { id:"tips", menu:"m_tips", action:"info",
    a:{ es:"La propina es *voluntaria*. En restaurantes suele sugerirse el 10% (puedes aceptarlo o no). A guías y conductores, si te gustó el servicio, una propina es muy apreciada. 💚",
        en:"Tipping is *voluntary*. Restaurants often suggest 10% (you may accept or decline). For guides and drivers, if you enjoyed the service, a tip is much appreciated. 💚",
        fr:"Le pourboire est *facultatif*. Les restaurants suggèrent souvent 10 % (libre à vous). Pour guides et chauffeurs, un pourboire est très apprécié. 💚",
        de:"Trinkgeld ist *freiwillig*. Restaurants schlagen oft 10 % vor (annehmen oder nicht). Für Guides/Fahrer ist ein Trinkgeld sehr willkommen. 💚",
        pt:"A gorjeta é *voluntária*. Restaurantes costumam sugerir 10% (você aceita ou não). Para guias e motoristas, se gostou, uma gorjeta é muito bem-vinda. 💚" } },
  { id:"phrases", menu:"m_phrases", action:"info",
    a:{ es:"¡Ya hablas español! 😄 Pero por si acaso: *Hola / Gracias / Por favor / ¿Cuánto cuesta? / ¿Dónde está el baño? / Un café, por favor / Ayuda*.",
        en:"Handy Spanish: *Hola* (hi) · *Gracias* (thanks) · *Por favor* (please) · *¿Cuánto cuesta?* (how much) · *¿Dónde está el baño?* (where's the toilet) · *Un café, por favor* · *Ayuda* (help).",
        fr:"Espagnol utile : *Hola* (bonjour) · *Gracias* (merci) · *Por favor* (s'il vous plaît) · *¿Cuánto cuesta?* (combien) · *¿Dónde está el baño?* (toilettes) · *Un café, por favor* · *Ayuda* (aide).",
        de:"Nützliches Spanisch: *Hola* (hallo) · *Gracias* (danke) · *Por favor* (bitte) · *¿Cuánto cuesta?* (wie viel) · *¿Dónde está el baño?* (Toilette) · *Un café, por favor* · *Ayuda* (Hilfe).",
        pt:"Espanhol útil: *Hola* (oi) · *Gracias* (obrigado) · *Por favor* · *¿Cuánto cuesta?* (quanto custa) · *¿Dónde está el baño?* (banheiro) · *Un café, por favor* · *Ayuda* (ajuda)." } },
  { id:"reco", menu:"m_reco", action:"info",
    a:{ es:"Imperdibles: *Valle de Cocora* (palma de cera), pueblos de colores *Salento y Filandia*, *café de origen* en finca, *termales* de Santa Rosa, miradores de la cordillera y *avistamiento de aves*. ¿Quieres algo fuera de lo común? Pregúntame por *Colombia inexplorada* y te armamos planes únicos.",
        en:"Must-sees: *Cocora Valley* (wax palms), colourful *Salento and Filandia*, *origin coffee* on a farm, *Santa Rosa hot springs*, mountain viewpoints and *birdwatching*. Want something off the beaten path? Ask about *unexplored Colombia* and we'll craft unique plans.",
        fr:"À ne pas manquer : *vallée de Cocora*, villages colorés *Salento et Filandia*, *café d'origine*, *thermes de Santa Rosa*, belvédères et *observation d'oiseaux*. Hors des sentiers ? Demandez la *Colombie inexplorée*.",
        de:"Highlights: *Cocora-Tal*, bunte Dörfer *Salento und Filandia*, *Ursprungskaffee*, *Thermen Santa Rosa*, Aussichtspunkte und *Vogelbeobachtung*. Abseits der Pfade? Fragen Sie nach dem *unerforschten Kolumbien*.",
        pt:"Imperdíveis: *Vale de Cocora*, vilarejos coloridos *Salento e Filandia*, *café de origem*, *termas de Santa Rosa*, mirantes e *observação de aves*. Quer algo fora do comum? Pergunte pela *Colômbia inexplorada*." } },
  { id:"emergency", menu:"m_emergency", action:"info",
    a:{ es:"🚨 Emergencias en Colombia: *123* (línea única). Policía 123 · Ambulancia 125 · Bomberos 119. Guarda también el número de tu anfitrión (abajo). Si estás en un recorrido, avisa a tu guía de inmediato.",
        en:"🚨 Emergencies in Colombia: *123* (single line). Police 123 · Ambulance 125 · Fire 119. Also save your host's number (below). On a tour, alert your guide immediately.",
        fr:"🚨 Urgences en Colombie : *123*. Police 123 · Ambulance 125 · Pompiers 119. Enregistrez aussi le numéro de votre hôte (ci-dessous). En excursion, prévenez votre guide.",
        de:"🚨 Notfälle in Kolumbien: *123*. Polizei 123 · Krankenwagen 125 · Feuerwehr 119. Speichern Sie auch die Nummer Ihres Gastgebers (unten). Auf Tour sofort Guide informieren.",
        pt:"🚨 Emergências na Colômbia: *123*. Polícia 123 · Ambulância 125 · Bombeiros 119. Salve também o número do seu anfitrião (abaixo). Em passeio, avise seu guia na hora." } }
];
